### ISSUE TITLE
Don't pollute the user's namespace with unnecessary symbols.

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#100]
```libumka.a``` takes the following symbols for itself:
<details>
<summary>libumka.a symbols</summary>

    umkaAddFunc
    umkaAddModule
    umkaAlloc
    umkaAsm
    umkaCall
    umkaCompile
    umkaFree
    umkaGetError
    umkaGetFunc
    umkaInit
    umkaRun
    blocksCurrent
    blocksEnter
    blocksFree
    blocksInit
    blocksLeave
    externalAdd
    externalFind
    externalFree
    externalInit
    moduleAdd
    moduleAddSource
    moduleAssertFind
    moduleFind
    moduleFindByPath
    moduleFindSource
    moduleFindSourceByPath
    moduleFree
    moduleGetImplLibFunc
    moduleInit
    storageFree
    storageInit
    compilerAsm
    compilerCall
    compilerCompile
    compilerFree
    compilerGetFunc
    compilerInit
    compilerRun
    constAssign
    constBinary
    constCallBuiltin
    constDeref
    constFree
    constInit
    constUnary
    constZero
    parseDecl
    parseProgram
    parseShortVarDecl
    parseType
    doApplyOperator
    doImplicitTypeConv
    doPushConst
    doPushVarPtr
    parseDesignator
    parseDesignatorList
    parseExpr
    parseExprList
    parseQualIdent
    genAsm
    genAssertRange
    genAssertType
    genAssertWeakPtr
    genAssign
    genBinary
    genCall
    genCallBuiltin
    genCallExtern
    genCallIndirect
    genCaseBlockEpilog
    genCaseBlockProlog
    genCaseExprEpilog
    genChangeRefCnt
    genChangeRefCntAssign
    genDeref
    genDup
    genElseProlog
    genEnterFrame
    genEnterFrameStub
    genEntryPoint
    genForCondEpilog
    genForCondProlog
    genForEpilog
    genForPostStmtEpilog
    genFree
    genGetArrayPtr
    genGetDynArrayPtr
    genGetFieldPtr
    genGoFromTo
    genGoFromToIf
    genGoto
    genGotoIf
    genGotosAddStub
    genGotosEpilog
    genGotosProlog
    genHalt
    genIfCondEpilog
    genIfElseEpilog
    genInit
    genLeaveFrame
    genLeaveFrameFixup
    genNop
    genPop
    genPopReg
    genPushGlobalPtr
    genPushIntConst
    genPushLocal
    genPushLocalPtr
    genPushRealConst
    genPushReg
    genPushStruct
    genPushUIntConst
    genReturn
    genShortCircuitEpilog
    genShortCircuitProlog
    genSwap
    genSwapAssign
    genSwapChangeRefCntAssign
    genSwitchCondEpilog
    genSwitchEpilog
    genTryRemoveImmediateEntryPoint
    genUnary
    genWhileCondEpilog
    genWhileCondProlog
    genWhileEpilog
    genZero
    identAddBuiltinFunc
    identAddConst
    identAddGlobalVar
    identAddLocalVar
    identAddType
    identAllocParam
    identAllocStack
    identAllocVar
    identAssertFind
    identFind
    identFree
    identInit
    identIsOuterLocalVar
    identTempVarName
    lexCheck
    lexEat
    lexFree
    lexInit
    lexNext
    lexNextForcedSemicolon
    lexShortAssignment
    lexSpelling
    rtlclock
    rtlfclose
    rtlfeof
    rtlfopen
    rtlfread
    rtlfseek
    rtlftell
    rtlfwrite
    rtlgetenv
    rtlremove
    rtltime
    doGarbageCollection
    doGarbageCollectionDownToBlock
    doResolveExtern
    doZeroVar
    parseAssignmentStmt
    parseDeclAssignmentStmt
    parseFnBlock
    parseFnPrototype
    typeAdd
    typeAddField
    typeAddParam
    typeAddPtrTo
    typeAssertCompatible
    typeAssertEquivalent
    typeAssertFindField
    typeAssertForwardResolved
    typeAssertValidOperator
    typeCompatible
    typeDeepCopy
    typeEquivalent
    typeFindField
    typeFindParam
    typeFree
    typeFreeFieldsAndParams
    typeGarbageCollected
    typeInit
    typeKindSpelling
    typeParamSizeTotal
    typeParamSizeUpTo
    typeSize
    typeSizeNoCheck
    typeSpelling
    typeValidOperator
    vmAsm
    vmFree
    vmInit
    vmReset
    vmRun

</details>

The ones prefixed with 'umka' are ok, but the rest have a chance to collide with symbols defined by the application, resulting in a linker error (multiple definition of `XXX', 'XXX' defined twice, etc.).

In order to avoid collisions I think the symbols need to have a prefix ('umka_' or 'um_' perhaps?). This would probably be a tedious refactoring.

**Comment by marekmaskarinec** [comment]
If this were to happen, this could help:
```bash
#!/usr/bin/env sh

cat symbols | while read -r func; do
    echo "$func"
    sed -i "s/$func/umka_$func/g" src/*.c src/*.h
done
```

`symbols` is file containing all the functions that should be replaced (one on each line).
