### ISSUE TITLE
Running umka from umka

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#105]
I have a very strange use case, where it would be useful to run umka from umka, however `umkaInit` fails. I think it is the function `setjmp`. Since it was already called once, it won't return 0 now. Would calling functions like `compilerInit` directly fix this?

**Comment by vtereshkov** [comment]
Hmm, a good question! I hoped Umka was reentrant, but never checked it. You are trying to call a C function from Umka that calls `umkaInit()`, correct? Do you pass a different `umka` instance to this second `unkaInit()`? How exactly does it fail?

**Comment by marekmaskarinec** [comment]
> You are trying to call a C function from Umka that calls umkaInit(), correct?

Yes.

> Do you pass a different umka instance to this second unkaInit()?

Yes, since the original umka is ran by the umka binary.

...

Update: I managed to run umka fron umka, but only if I "link" it by including all the umka c files in the build. If I do it like this `-Ldir -lumka` or like this `dir/libumka.a`, it doesn't work.

Even though I managed to run the program, it got an error because of unresolved prototype, which comes from an umi library, the same one that called the script, but that might be my mistake. I will try making the project available soon, so you have bigger context.

**Comment by vtereshkov** [comment]
I don't quite understand what to build and what to run. I see two scripts in the repository, but both fail (or not ?):
```
vtereshkov@Vasiliy-Acer:~/cake/src$ ./extern-build-shared.sh 
cc: warning: ../lib/umka-lang/build/libumka.a: linker input file unused because linking not done
vtereshkov@Vasiliy-Acer:~/cake/src$ ./extern-build-static.sh 
cc: warning: ../lib/tinycc/libtcc.a: linker input file unused because linking not done

```

**Comment by marekmaskarinec** [comment]
I think this happens, because I link files to objects. The build does not fail though. You run it like this: `umka src/main.um run/build src/main.um`. Run should run itself (this is where I try to run umka) and build should make a binary called main.

**Comment by vtereshkov** [comment]
I have managed to run Umka in a chained fashion in a tiny demo project. Under Windows this is trivial. Under Linux, this poses a small problem. Just as we place `./` before an executable name in the current folder, I have had to place `./` before the UMI header file name in the `import` clause:
```
import "./launcher.um"
```
Otherwise, I get the `Unresolved prototype of launch` error.

You can look at the project: [chain.zip](https://github.com/vtereshkov/umka-lang/files/6797806/chain.zip). Run it with
```
./build_launcher_linux.sh
./umka step1.um
```
Both Step 1 and Step 2 Umkas use the same `libumka.so`.

**Comment by marekmaskarinec** [comment]
Interesting. Is the need for `./` a dlopen thing? Couldn't umka just add it automatically?

**Comment by vtereshkov** [comment]
> Interesting. Is the need for ./ a dlopen thing? Couldn't umka just add it automatically?

It's a plausible explanation. I have to investigate it further.

**Comment by vtereshkov** [comment]
Possibly fixed.

**Comment by vtereshkov** [comment]
On the other hand, it seems to me suspicious that you propose to run `umka src/main.um run src/main.um`. Are you sure you don't have an infinite recursion here? When I replace `launcher.launch("step2.um")` with `launcher.launch("step1.um")` in my demo project, I (obviously) get a segmentation fault.

**Comment by marekmaskarinec** [comment]
I updated umka and played with the linker flags a bit and now it works both with a simple program and itself, which depends on a `.umi` library. I'm not sure, which one of them fixed it.

> On the other hand, it seems to me suspicious that you propose to run umka src/main.um run src/main.um. Are you sure you don't have an infinite recursion here?

No, it won't. There aren't any arguments passed to the second instance, so it will just print "not enough arguments" and exit.

Should I close this?
