### ISSUE TITLE
Typecasting arrays to []interface{}

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#106]
I think arrays like `[]int` should be castable to []interface{} and back. This would make `fnc.um` much more usable. From my understanding, now you have to initialize an array of type fnc.AnyArr for it to work, which I think isn't viable.

Something like this would be cool:
```go
fn main() {
    intArr := []int{5, 6, 7, 1, 2, 3}

    printf("%s\n", repr(^[]int(^[]interface{}(intArr).map(
        fn (x, ctx: fnc.Any): fnc.Any {
            return ^int(x)^ * ^int(ctx)^
        }, 10))^))
}
```

But it fails with the invalid type cast error.

**Comment by vtereshkov** [comment]
I have to think of it carefully. For example, Go doesn't allow such conversions: https://golang.org/doc/faq#convert_slice_of_interface

**Comment by marekmaskarinec** [comment]
I think umka, a more high level language than go, could use this feature. There are already other abstractions with interfaces (like casting non-pointer values to interfaces).

**Comment by vtereshkov** [comment]
Perhaps you are right (but anyway, please keep in mind that Go can easily store a non-pointer in an interface: https://play.golang.org/p/F87MyB2a_IL).

**Comment by skejeton** [comment]
I'm bumping this issue because I have the same problem

**Comment by vtereshkov** [comment]
@skejeton Then how should we handle this?
```
fn main() {
        intArr := []int{5, 6, 7, 1, 2, 3}
        genArr := []interface{}(intArr)
        genArr = append(genArr, "Hello World")
        intArr2 := []int(genArr)
        printf(repr(intArr2) + '\n')
}
```
Should we also allow casting `[]interface{}` to `[]^int{}` in this case, so that the user could check `[]^int{}` for `null`s?

**Comment by marekmaskarinec** [comment]
I think you should be able to cast to `[]int` and `^[]int`, not `[]^int`. For
the former, a value with the wrong type would cause a runtime error. For the
latter, the result would just be null. This way you won't have to allocate
memory for every element and the user won't have to check the whole array. If
the user wanted to check what elements can be converted, they can just iterate
the array and convert them one by one.

**Comment by vtereshkov** [comment]
Done. The original example can now be written as follows:
```
import "import/fnc.um"

fn main() {
    intArr := []int{5, 6, 7, 1, 2, 3}

    printf("%s\n", repr([]int(fnc.AnyArray(intArr).mapEach(
        fn (x, ctx: fnc.Any): fnc.Any {
            return int(x) * int(ctx)
        }, 10))))
}
```
