### ISSUE TITLE
Embed std.um into Umka binary

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#107]
In order to make the Umka interpreter self-contained, the `std.um` module should be embedded into the interpreter binary. The C implementation of `std.um` is already there, so it is unreasonable to keep the corresponding Umka bindings in a separate file.

@marekmaskarinec Please be prepared for this change.

**Comment by marekmaskarinec** [comment]
I think `map.um`, `fnc.um` and `mat.um` should be embedded too.

**Comment by vtereshkov** [comment]
@marekmaskarinec This is possible, but I don't consider these modules to be an integral part of the interpreter. Maybe in the future we will have more library modules in the standard Umka distribution (possibly your `libs`?). This does not mean they all should be compiled into the Umka core binary, which I would like to keep minimalistic.

As for `std.um`, the picture is different: I already have, for example, `fscanf()` and `fprintf()` as built-in core functions, but they cannot be used without having `std.um` since the `File` type is defined there. So the Umka core binary is not self-consistent.

**Comment by marekmaskarinec** [comment]
Good point, although I think `map.um` should be embedded, since umka doesn't have maps by default.
