### ISSUE TITLE
Optimizer bug when indexing an array via a global

### ISSUE THREAD

**Issue by ishdx2** [vtereshkov/umka-lang#117]
minimal example:
```go
x := 0

fn something(): int {
        arr := [1]int{0}
        return arr[x]
}
```

causes this error:
```
Error test.um (6, 1): Index -62545008 is out of range 0...0
```

Umka interpreter (build Oct 11 2021)

**Comment by vtereshkov** [comment]
@ishdx2 Thank you for reporting an interesting bug. However, your PR is not quite correct. The `tokKind` field is never filled for the `OP_PUSH` instruction. So your code completely disables the optimization. We have to analyze the `typeKind` field instead.
