### ISSUE TITLE
is mac && silicon support ?

### ISSUE THREAD

**Issue by Berrserker** [vtereshkov/umka-lang#121]

**Comment by vtereshkov** [comment]
@Berrserker Do you mean the Apple's new ARM-based CPUs? No one has tested Umka on such machines. However:

- Some time ago I successfully compiled and run Umka on an Aarch64 (NVIDIA Jetson TX2), which is a 64-bit ARM.
- Other people compiled Umka for x86-based Macs.

Umka has problems on machines that forbid unaligned memory access (SPARCs, some old ARMs). However, for newer ARMs this is no longer a problem. So you can try to build Umka on your machine.

**Comment by vtereshkov** [comment]
Closing the issue. Feel free to reopen it if you have any problems or further questions.
