### ISSUE TITLE
Circular struct members

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#123]
Currently umka allows structs to reference structs of the same type, but doesn't allow referencing undeclared structs or struct prototypes. This means code like this doesn't work.
```go
type Tile* = struct {
    parent: ^Segment
    index: int
    rotation: int
    pos: th.Vf2
}

// Switch is multiple segments ending in one place. Even a simple signal is a switch,
// but with only two segments.
type Switch* = struct {
    segs: []^Segment
    // which end of respective segment is part of the switch
    ends: []int
    pos: th.Vf2
}

type Segment* = struct {
    switches: ^[2]Switch
    tiles: []Tile
}
```

Solution can be to use `interface{}` everywhere, but it can get annoying with type assertions all over the place. In my case I have the advantage of all segments being stored in one array, so i can just store their index.

**Comment by vtereshkov** [comment]
@marekmaskarinec Sorry for the delay. This is possible in Umka, but only if all the related types are declared in the same declaration list `()`. This code works:
```
type (
    Tile* = struct {
        parent: ^Segment
        index: int
        rotation: int
        pos: th.Vf2
    }

    // Switch is multiple segments ending in one place. Even a simple signal is a switch,
    // but with only two segments.
    Switch* = struct {
        segs: []^Segment
        // which end of respective segment is part of the switch
        ends: []int
        pos: th.Vf2
    }

    Segment* = struct {
        switches: ^[2]Switch
        tiles: []Tile
    }
)
```
Unfortunatunately, this has a natural limitation that all the types must be declared in the same module. I'm already thinking on how to overcome this limitation, but cannot come up with a solution yet.

**Comment by marekmaskarinec** [comment]
Works with the declaration list.
