### ISSUE TITLE
Adding DynArr to umka api

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#125]
I think it would be good if DynArr was added to the umka api. This would mean you don't need to create special structs with `data: ^T; len: int` in umka, but can pass almost all structs (except interfaces). It could also be implemented as a macro:
```c
#define UmkaDynArr(T) struct { struct tagType *_type; int64_t len; int_64_t itemSize;  T *data }
```
So casting from `void *` isn't needed all the time.

**Comment by vtereshkov** [comment]
@marekmaskarinec This may be a good idea, provided that the structure is always treated as read-only in C. If, for example, a user tries to modify `len` or construct a new `DynArr` to return from the C function, it would be a disaster.
