### ISSUE TITLE
Null for types other than pointers

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#128]
Uninitialized strings, dynamic arrays, interfaces, functions or fibers are in an invalid (null) state. An attempt to use them causes a runtime error like `String is null`. However, there is no way to check them for being null or reset them back to the null state.

**Comment by marekmaskarinec** [comment]
I think these types should work even if their value is null. For example appending a null array will just allocate the array instead of erroring and calling a null function won't do nothing.

**Comment by vtereshkov** [comment]
@marekmaskarinec As for dynamic arrays, you are probably right (even though Go distinguishes between empty slices and `nil` slices). But this may be meaningless for the other types. Suppose I have a function variable whose history I don't know. Am I allowed to call it or I immediately get a runtime error? The same applies to interfaces and fibers. As for strings, I'm not sure whether to treat null strings just as empty strings.

**Comment by vtereshkov** [comment]
Not implemented for fibers. Need to rethink fibers altogether.
