### ISSUE TITLE
moduleLoadImtlLib won't work with absolute path

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#129]
If module's folder is an absolute path, umka will prefix it with `./` before loading it, meaning it won't be found. This can't be fixed by just removing the `./` prefix as without it, it doesn't work for dynamic paths.

**Comment by vtereshkov** [comment]
Hopefully fixed. Please check.

**Comment by marekmaskarinec** [comment]
Yes. It works.
