### ISSUE TITLE
Slicing empty

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#144]
Consider making empty slices valid. Often some checks are necessary to prevent crashing by trying to produce empty slice.
```
fn decode*(s: str): []Rune {
	runes := make([]Rune, len(s))
	runeCount := 0

	l := len(s)
	for i := 0; i < l; runeCount++ {
		runes[runeCount] = getNextRune(s, i)
		i += runes[runeCount].size()
	}

	return slice(runes, 0, runeCount)
}
```
in this case if runeCount is 0, return statement, `slice(runes, 0, runeCount)`, will expand to `slice(runes, 0, 0)`. Which should result in an empty slice, but in reality produces an error.
If we follow golang, empty slices are allowed.
```go
package main

import "fmt"

func main() {
	primes := [6]int{2, 3, 5, 7, 11, 13}

	var s []int = primes[0:0]
	fmt.Println(s)
}
```
So in my opinion slicing with 0 size should be valid.

**Comment by vtereshkov** [comment]
@skejeton By the way, the Go example you provided is not relevant, since the problem only occured in Umka when the index was beyond the upper bound, i.e., when constructing `primes[6:6]`.

**Comment by skejeton** [comment]
@vtereshkov thanks, makes sense
