### ISSUE TITLE
Imported module folder ignored if module is imported twice from different modules

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#145]
```
// utils.um
fn f*() {printf("1")}

// lib.um
import "abracadabra/utils.um"  // <--- No "abracadabra" folder exists, should print an error
// Some stuff

// test.um
import (
        "utils.um"
        "lib.um"
)

fn main() {
        utils.f()           // <--- Prints 1
}
```

**Comment by vtereshkov** [comment]
Another pathological example:
```
import (
        "lib1/lib.um"
        "lib2/lib.um"           // <--- Error: Duplicate import of lib
)

fn main() {
}
```

**Comment by vtereshkov** [comment]
Sometimes Umka even silently imports a wrong module:
```
// lib1/utils.um
fn f*() {printf("1\n")}

// lib1/lib1.um
import "utils.um"
fn f*() {utils.f()}

// lib2/utils.um
fn f*() {printf("2\n")}

// lib2/lib2.um
import "utils.um"
fn f*() {utils.f()}

// test.um
import (
        "lib1/lib1.um"
        "lib2/lib2.um"
)

fn main() {
        lib1.f()        // <--- Prints 1
        lib2.f()        // <--- Prints 1 (?!)
}
```

**Comment by skejeton** [comment]
I think this has happened to me with some of tophat modules (i'm not sure)

**Comment by vtereshkov** [comment]
@skejeton I'm afraid this may (or even should) happen in any large Umka project. Even worse, Umka is now unable to detect name clashes properly. 

The only workaround available now is to avoid duplicate module names throughout the project, including all third-party libraries and embedded modules. 

At a deeper level, this issue is related to the fact that a file path cannot be used as a unique file ID. For example, `file.um`, `../folder/file.um`, `../folder/../folder/file.um` etc. refer to the same file.

This issue blocks #136.

**Comment by marekmaskarinec** [comment]
> At a deeper level, this issue is related to the fact that a file path cannot be used as a unique file ID. For example, file.um , ../folder/file.um , ../folder/../folder/file.um etc. refer to the same file.

This could be fixed by implementing something like go's  [filepath.Clean](https://pkg.go.dev/path/filepath#Clean).

**Comment by vtereshkov** [comment]
@marekmaskarinec An interesting idea! However, I'm not sure how to prove *lexically* that a absolute path is equivalent to a relative path. Involve the current directory too?

There is https://en.cppreference.com/w/cpp/filesystem/equivalent, but it is only supported in C++17 and its implementation is heavily platform-dependent.

**Comment by skejeton** [comment]
and this wouldn't work with symlinks. that said, you need to make sure the file inode is the same, not the path. and this has to be made cross platform

**Comment by vtereshkov** [comment]
For now, I implemented a purely lexical approach. Thanks to @marekmaskarinec for [filepath.Clean](https://pkg.go.dev/path/filepath#Clean).
