### ISSUE TITLE
Ability to explicitly cast newtype structure to it's parent type

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#146]
```
type SomeLongStructureName = struct {
        a, b: int
}

fn test(t: SomeLongStructureName) {
        printf("%s\n", repr(t))
}

fn main() {
        type S = SomeLongStructureName
        l := []S{S{32, 64}, S{43, 34}}
        test(SomeLongStructureName(l[0]))
}
```
S is the derivative of SomeLongStructureName, I don't think it should be implicitly possible to pass S as a SomeLongStructureName, however I think it would be useful to be able to cast it explicitly, so you can use S as a shorthand name to construct big tables of data.

**Comment by vtereshkov** [comment]
@skejeton I'll consider this improvement, though you can always use a pointer type cast as a workaround, provided that your structure doesn't contain any pointer fields: `test(^SomeLongStructureName(&l[0])^)`.
