### ISSUE TITLE
String module

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#157]
Currently there's only few limited string operations in std.um and utf8.um.
There are some string operations that would be useful:
* `split` Splits the string by specified token
* `repeat` Repeats the string over and over N times
* `toLower` `toUpper` transforms each character to lowercase/uppercase respectively
* `map` Iterates over each character to produce a transformed string (UTF8 module?)
* `join` Joins array of strings into one string by specified token 
* `find` Finds sub-string in a string
* `match` Matches regex against a string (Regex module?)
* `replace` Replaces regex matches in a string (Regex module?)
* string builder? (I think sprintf is enough, but either way)

**Comment by marekmaskarinec** [comment]
I made a small strings library.
https://github.com/marekmaskarinec/coulau/blob/main/strings.um

Some of the implementations are questionable, but it works well enough for me.

**Comment by marekmaskarinec** [comment]
@skejeton I implemented a regex library: https://github.com/marekmaskarinec/regum

**Comment by vtereshkov** [comment]
Implemented as an UmBox package: https://umbox.tophat2d.dev/package/strings
