### ISSUE TITLE
Why can I return a module-private struct from an exported function and use it?

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#158]
This shouldn't be legal as I don't really have access to the struct symbol.

https://github.com/marekmaskarinec/tophat/issues/30#issuecomment-1158684630

**Comment by vtereshkov** [comment]
@skejeton You cannot access the type identifier, but you can access the type. Go and C++ seem to behave similarly:

https://go.dev/play/p/OL8FfakPrt3
https://onlinegdb.com/HrSxJG2Gu

**Comment by skejeton** [comment]
Bumping this issue, just as an idea, returning module private types from exported functions may be used for opaque types, where you can not access the fields but can hold and pass it around.
