### ISSUE TITLE
The map type should preferably be a built in and type checked like in Go

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#161]
It's all over the place in UI code, World Chunk code, etc. It's honestly pretty useful, but not really in the current form.

https://github.com/marekmaskarinec/tophat/issues/30#issuecomment-1158684630

**Comment by vtereshkov** [comment]
@skejeton Of the "big" tasks mentioned in your report, this one seems to be the only one that can be done in the foreseeable future.

By the way, I realized that my current map implementation does not even have an iterator. For today, I should at least fix this.

**Comment by skejeton** [comment]
YES! I forgot to mention it, but iterator is something I've needed indeed. I've been using the implementation detail instead where you iterate over buckets

**Comment by vtereshkov** [comment]
@marekmaskarinec @skejeton Maps as a core data type are nearly complete (see, however, #167). Please test them in your projects.

**Comment by skejeton** [comment]
@vtereshkov I'll test it tomorrow monday :+1:
