### ISSUE TITLE
Iterating by pointer / No way to iterate a map without copying the value

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#172]
Map offers `for k, v in some_map` to get the key and the value, but the value is copied. It might not be desirable to copy the value in hotspots (like my world rendering code where the `v` would be a copy of a chunk). The second map iteration method `for v in some_map` only gives you the value, no key. So as it looks like, it's impossible to iterate the map without copying the value. This is undesirable when you are trying to iterate a map with intentions to mutate it, because you'll have to get the reference of the original by accessing map with a key.

There's 2 solutions I can think of:
1. Allow iterating by reference.. This would be soo convenient. Essentially you can do `for k, &v in some_map`. This would be very useful for mutative iterations (and arguably non copying). As an alternative option you can do `for k, ^v in some_map`. The syntax is up to choice, for me, it doesn't matter.
2. Iterate by keys instead of values by default, like in go you can do `for k in some_map`. This would be a nice feature for go parity, and it just makes sense, since a lot of times when you access a map you also want to know the key. (at least, in all my cases I've ever used a map)
3. Both. Really! This would be super nice, and just good things to add for milestone Umka 1.0.

**Comment by vtereshkov** [comment]
CC @marekmaskarinec

**Comment by vtereshkov** [comment]
@marekmaskarinec Having `for ^x in a` (i. e., accessing by pointer) is a separate task (proposal 1 in @skejeton 's comment). Now the question is about proposal 2: should `x` in `for x in a` be treated as the index/key or as the value? Now it is a value (in C++/Python style). Should it instead be an index/key (more Go/JS-ish)?

**Comment by skejeton** [comment]
Sweet I think this can be closed, since it solves the original problem. For iterating by reference a new issue can be added instead.

**Comment by vtereshkov** [comment]
Closing. Please open a separate issue.

**Comment by vtereshkov** [comment]
```
// A 3x performance improvement

import "std.um"

var a: [1000][100]int

fn main() {
        start := std.clock()

        for cnt := 0; cnt < 100000; cnt++ {
                for i in a {
                        a[i][0] = i
                }
        }

        printf("Time: " + repr(std.clock() - start) + '\n')             
} 
```

**Comment by skejeton** [comment]
So as I understand arrays are now also iterated by indices?

**Comment by skejeton** [comment]
Thanks for the info
