### ISSUE TITLE
Module name and variable collision

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#173]
Very often when I'm writing Umka code I use trivial names. This is fine, except for when I load module `font`, then every instance of name `font` except for struct fields has to be renamed, because it now collides with the module name. This happened to me recently with UI code, where I had Window struct and a bunch of usages of word "window". When I tried importing Tophat's "window.um", it all broke and I had to change about 40 instances of window along 600 lines of code. Thankfully it's pretty trivial and took barely 5 minutes. But I think this can be improved.

1. Allow to alias module names, like `import (th_window "window.um")`
2. Allow shadowing modules, but instead make them accessible through a certain prefix like `.`
   So when you want to access window.um you do `.window.width`, like C++'s `::` prefix to address global namespace. I prefer this to first option because this will keep names of modules consistent across the project while fixing this problem. Unfortunately this won't solve problem with module name collisions.

**Comment by skejeton** [comment]
Module collision is interesting thing to think about too, because you could have 2 API's both with `window` modules that you need to use somehow together.

**Comment by skejeton** [comment]
:point_right: #175

**Comment by vtereshkov** [comment]
@skejeton @marekmaskarinec I implemented module aliases (proposal 1) in the form `import mod = "folder/mod.um"`. Please test them.

**Comment by skejeton** [comment]
@vtereshkov They work wonders! Very useful indeed. Thank you
