### ISSUE TITLE
Ability to define a types and functions in the global scope

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#176]
This would useful in tophat for types like `th.Vf2` of `th.f/u/iu`.

It doesn't have to be a part of the language itself, but just part of the umka api.

**Comment by vtereshkov** [comment]
@marekmaskarinec Where (i.e., in what module) should these identifiers be declared?

Or is having them in `th.um` no longer a problem?

**Comment by marekmaskarinec** [comment]
I don't need this for anything now.
