### ISSUE TITLE
Downcasting signature with default value to signature without default value in interface implementation

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#195]
```go
import ("std.um")

type Test = interface {
  function(param: int)
}

type Impl = struct {};

fn (i: ^Impl) function(param: int = 1) {
}

fn check(x: Test) {
  x.function(1)
}

fn main() {
  var t: Impl
  check(t) // <- Method function has incompatible signature
}
```

Technically the signatures are pretty much the same, or rather, the signature from the implementation should be convertible to the signature of the interface

**Comment by vtereshkov** [comment]
@skejeton It's unclear to me why they should be convertible. I can call `i.function()` but I cannot call `t.function()`, so the signatures are quite different. If we allow such conversions, the next question would be, why not allow converting `fn (x: int32)` to `fn (x: int)`, etc, etc.

I'd rather fix a bug that now allows such conversions for zero default values, like `fn (i: ^Impl) function(param: int = 0)`.

**Comment by skejeton** [comment]
`fn (x: int32)` to `fn (x: int)` isn't valid because they are different function signatures, but functions with default values but the same signature it's just that at call the default value is inlined into the call (or that's what I assume happens). down casting default parameters doesn't change the calling ABI of a function, unless I misunderstand the current implementation. In my case I have a font struct with a default of 1.0 value specified for scale in draw method, and a ui Text Renderer interface which expects a mandatory scale parameter
