### ISSUE TITLE
"Stack use after scope" warning if map references stack item

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#198]
```
type Thing = struct {
  children: map[str]^Thing
  parent: ^Thing
}

type X = struct {
  things: Thing
}

fn main() {
  x := X{things: Thing{children: map[str]^Thing{}}}
  newChild := new(Thing)
  newChild.parent = &x.things

  x.things.children["test"] = newChild
}
```

![image](https://user-images.githubusercontent.com/27076041/184547426-54881342-07fd-496a-90cd-3cdee745a675.png)

**Comment by skejeton** [comment]
removing this line changes nothing, i guess it crashes at the parent assignment
```
  x.things.children["test"] = newChild
```

**Comment by vtereshkov** [comment]
@skejeton Cannot reproduce the segfault on Windows or in the playground. The application terminates normally. Did you really see a segfault or just an address sanitizer report?

**Comment by skejeton** [comment]
I can't reproduce it without the sanitizer, but I believe sanitizer might be correct here

**Comment by skejeton** [comment]
I didn't change any code, so the line numbers it reports should be correct

**Comment by vtereshkov** [comment]
A minimum example:
```
type T = struct {
  children: map[str]^T
}

fn f() {
    var t: T
}               // ERROR: AddressSanitizer: stack-use-after-scope

fn main() {
    f()
}
```
