### ISSUE TITLE
Why a custom heap?

### ISSUE THREAD

**Issue by Lucrecious** [vtereshkov/umka-lang#202]
Hi

This is a very cool project! I am working on my own language and I was looking through statically-typed open source languages to see their implementations, and noticed Umka had a custom heap implementation.

Is there a reason for doing this rather than using C's heap implementation?

I'm asking this here because I don't know where else to ask - hope that's okay!

**Comment by vtereshkov** [comment]
@Lucrecious I don't quite understand what you call a 'custom heap', but I guess you mean `chunkAlloc()`.

Like in all other scripting languages, Umka has garbage collection (based on reference counting, in my case). Every allocated memory block has a reference count. When this count reaches zero, the block is automatically deallocated. From the user's standpoint, this means that he does not need to explicitly call `free()` for each `malloc()`, he just calls `chunkAlloc()` that performs all necessary bookkeeping.

Of course, `chunkAlloc()` relies on the good old `malloc()` under the hood. Here it is: 

https://github.com/vtereshkov/umka-lang/blob/master/src/umka_vm.c#L147

**Comment by vtereshkov** [comment]
For better performance, the heap memory is actually allocated in pages, rather than in chunks, to avoid very long lists of small individual chunks that are hard to traverse fast.
