### ISSUE TITLE
Conflict within module if you name a global symbol same as the current module

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#203]
test.um:
```go
fn test() {}
```
Output:
```
Conflict between module
test and identifier test
```

**Comment by vtereshkov** [comment]
This helps avoid ambiguities like `test.value` (a variable `value` from module `test` or a field `value` from structure `test`?)

**Comment by skejeton** [comment]
Is it compiler ambiguities or?

**Comment by vtereshkov** [comment]
Yes, parsing ambiguities.

**Comment by skejeton** [comment]
@vtereshkov but the module can reference itself without the need of using it's explicit name
