### ISSUE TITLE
Boolean xor.

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#204]
Bool xor is useful for inverting bools inline:
```
fn putButton(b: ButtonState, reverted: bool) {
  drawButton(b, b.pressed~reverted)
}
```

If reverted isn't set, the code above will make the button appear pressed when it's pressed, and released when it's released, setting reverted to true will invert that, and make button appear pressed when released, and released when pressed.

**Comment by vtereshkov** [comment]
You can use `!=`:  `b.pressed != reverted`.

**Comment by skejeton** [comment]
you're right. I forgot they are the same
