### ISSUE TITLE
Overflow checking

### ISSUE THREAD

**Issue by tankf33der** [vtereshkov/umka-lang#21]
```
$ cat mike.um
import "import/std.um"
fn main() {
    var r: int8
    r = 0xff
    std.println(repr(r))
}
$ umka mike.um
-1
```

**Comment by vtereshkov** [comment]
Do you expect to have overflow checking?

**Comment by tankf33der** [comment]
ah, this sweet word "checking".
you dont want "checking" in this case too, right?

```
$ cat mike.um
fn main () {
    h := make([]int, 3)
    h[-1] = -1
}
$ ./umka mike.um

Runtime error mike.um (3): Index is out of range
Memory leak at 0x7f21c7152010 (2 refs)
$
```

If you so brave then you should add text to REAMDE.md file:
```
Overflow and bound checks are problems on coder's side. This is not umka's problem.
```

**Comment by vtereshkov** [comment]
The essence of this issue isn't clear from the title and description. Is it a problem with `repr()`? No. With `int8`? No. But OK, thank you for clarifying.
