### ISSUE TITLE
Dynamic array or string assignments copy just the pointer.

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#214]
```
fn main() {
  a := []str{"hi"}
  b := a

  a[0] = "huh"
  printf("%s\n", b[0])
}
```
What happened here? We copied `a` to `b` where the value was "hi", but after changing `a` to say "huh" the change also reflected in `b` although we didn't change `b`. It seems like it only copies the pointer on assignment. This doesn't happen with statically sized arrays. 
The current workaround would be `append(a, []str{})`. Copying is a reasonable choice because the current array operations are all copying (append, insert, delete). There may be a performance penalty introduced with this as you are now copying the entire data not just the pointer, however this can mostly be solved by implementing copy-on-write, where `b` would be assigned pointer to `a`, and if you write to either `a` or `b`, `b` would be copied. 

#160

**Comment by vtereshkov** [comment]
> It seems like it only copies the pointer on assignment. This doesn't happen with statically sized arrays.

Currently this is the intended behavior, as stated in the language specification:

_"Dynamic array assignment copies the pointer, but not the contents of the array."_

Furthermore, Go behaves similarly: https://go.dev/play/p/aQdUyoL33mD. However, Go provides `copy()` that copies the slice contents. Introducing `copy()` was one of my proposals for #160, though I'd prefer another syntax: `b := copy(a)`.

> Copying is a reasonable choice because the current array operations are all copying (append, insert, delete)

Not sure that copying is a good choice even for `append()`, `insert()` and `delete()`. If we change the semantics of `append()`, we'll perhaps have to do the same with `insert()` and `delete()`.

> this can mostly be solved by implementing copy-on-write

It's very difficult to do in the current architecture. 

All in all, I'll think of whether it's better to change the assignment semantics as you proposed, or to implement `copy()`. Anyway, it should be decided before doing anything with `append()`.

**Comment by skejeton** [comment]
Alright. Copy is good

**Comment by vtereshkov** [comment]
This discussion makes me think that we need immutable strings. Otherwise, we'll face troubles:
```
fn main() {
  a := "lies"
  b := a

  a[0] = 'd'
  printf("%s\n", b)        // "dies"
}
```
