### ISSUE TITLE
Warnings: unnecessary parenthesis warning

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#216]
```
if (x) { // WARN: Unnecessary parenthesis

}
```

May need be optional

**Comment by vtereshkov** [comment]
@skejeton I don't think that extra parentheses is an issue. It's more about one's taste and style. In your example they are obviously unnecessary. But what about `if (a == b) || (b == c) {}` or `isEqual = (a == b)`? They are still superfluous for the interpreter, but may improve readability.
