### ISSUE TITLE
Something like `atexit`

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#219]
`atexit` allows you to run some code before exit. In my case I want to save the editor layouts and other code when the program exits. I can do it at the end of main, but in case of runtime errors or other preemptive exits or multiple exit points, the program may not save the data I want.

**Comment by RobLoach** [comment]
Many languages have adopted the `defer` keyword, like [Go's `defer`](https://go.dev/tour/flowcontrol/12) and [C3's `defer`](https://www.c3-lang.org/examples/#defer).

**Comment by marekmaskarinec** [comment]
@skejeton for your specific use case I could add an `atexit` to tophat, but I think it would be better to see it being an umka feature.

**Comment by skejeton** [comment]
Defer seems to exit on the end of scope, not exactly what I want it appears

**Comment by vtereshkov** [comment]
The reported use case is now covered by `window.onDestroy.register({/*...*/})` in tophat.
