### ISSUE TITLE
Visual Studio Code plugin.

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#220]
For now the only visual studio code plugin for Umka is made by marek, but it's quite outdated, and highlights very few things, not even block comments. It's only reasonable to make this plugin as visual studio code is still one of the most widespread text editors.

**Comment by marekmaskarinec** [comment]
The way I see it is:
1. Add missing features to the current extensions
1. Link the extension in the main repo readme

**Comment by skejeton** [comment]
Exactly

**Comment by vtereshkov** [comment]
https://marketplace.visualstudio.com/items?itemName=mrms.vscode-umka
