### ISSUE TITLE
1 Language Grammar to Rule Them All

### ISSUE THREAD

**Issue by konsumer** [vtereshkov/umka-lang#222]
I would really like to make a live, syntax-highlighting web editor for umka, but I need a grammar definition for codemirror (or any other similar editor.)

I saw the [sublime language file](https://github.com/vtereshkov/umka-lang/blob/master/Umka.sublime-syntax), and tried it in sublime (pretty decent) and the [textmate grammar file](https://github.com/marekmaskarinec/vscode-umka/blob/master/syntaxes/umka.tmLanguage.json) in the VSCode plugin, and the [vim def](https://github.com/marekmaskarinec/vim-umka/blob/main/syntax/umka.vim) but none of the automatic converters I found worked with those.

I think a central simple format that can convert to other things like [this](https://github.com/foo123/editor-grammar/) would make it easier to generate grammars for other things, and [here](https://foo123.github.io/examples/ace-grammar/) is a nice live-editor for the grammar, but I think it's a bit beyond me. 

Related comic:
![XKCD Standards](https://imgs.xkcd.com/comics/standards_2x.png)

**Comment by konsumer** [comment]
Possibly related to #220

**Comment by vtereshkov** [comment]
@konsumer If the "grammar" you're talking about is just the lexical contents (i.e., highlighted tokens), I suppose it's quite easy to write a CodeMirror syntax definition file by hand. If you find a syntax definition file for Go, its adaptation for Umka will be straightforward. Having a set of syntax definition files in Umka distributions would be a plus, but only for the most popular editors, like VSCode, Sublime Text, or Vim. 

If the "grammar" is a set of syntactic rules, it's defined in the EBNF form in the language specification: https://github.com/vtereshkov/umka-lang/blob/master/spec.md#appendix-language-grammar

**Comment by konsumer** [comment]
My thinking is a central format that can produce other formats. For example, I want codemirror live-web-editor for umka (for playground) but I'd need to make the grammar for that by hand (which I am not great at.) I also think it would be useful to have vscode, sublime, etc. If it was all made from the same syntax-hilighting grammar source, we could keep that high quality, and just generate whatever was needed for lots of different targets.

**Comment by skejeton** [comment]
> My thinking is a central format that can produce other formats. For example, I want codemirror live-web-editor for umka (for playground) but I'd need to make the grammar for that by hand (which I am not great at.) I also think it would be useful to have vscode, sublime, etc. If it was all made from the same syntax-hilighting grammar source, we could keep that high quality, and just generate whatever was needed for lots of different targets.

I completely agree

**Comment by skejeton** [comment]
that said, EBNF format seems enough

**Comment by skejeton** [comment]
I'll write a converter application

**Comment by konsumer** [comment]
> that said, EBNF format seems enough

Yep, agreed, I didn't know about this when I initially asked. I guess all I mean is "let's not maintain like 5 separate grammars, let's make a central one that can be converted into the others programmatically."

> I'll write a converter application
Lemme know if I can help. If you can generate a few good ones, I can probly port that to codmirror and ace. Having syntax-hilighting in playground would be sick!
