### ISSUE TITLE
CudaText lexer

### ISSUE THREAD

**Issue by ghost** [vtereshkov/umka-lang#223]
@vtereshkov CudaText already has a Go lexer. Could you use it to make an Umka lexer? I asked the CudaText developer but he said I had to make it myself or doing a youtube review of his editor in exchange. I can't do any of it! Call me a stupid incompetent loser but I swear I feared regular expressions so much and CudaText lexer is full of them! Regular expression is something I completely don't understand. If I need to use it, I will Google and copy it and paste to my editor to get the job done and then forget it immediately.

https://github.com/Alexey-T/CudaText/issues/4515

**Comment by vtereshkov** [comment]
@ghost Why do we need to do this? I have never heard of CudaText. You seem to not use it either.
