### ISSUE TITLE
Proposal: Delegates

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#228]
As Umka doesn't support closures, they have to be simulated with interfaces. Here is a toy example inspired by my current work:
```
type PointCloud = struct {
        pts: [][3]real
}

fn (pc: ^PointCloud) add(p: [3]real) {
	pc.pts = append(pc.pts, p)
}

fn (pc: ^PointCloud) do(p: [3]real) {   // For compatibility with the callback interface
	pc.add(p)
}

fn readPoints(onPoint: interface{do(p: [3]real)}) {
	for i := 0; i < 10; i++ {
		onPoint.do([3]real{i + 10, i + 20, i + 30})		
	}
}

fn main() {
	var pc: PointCloud
	readPoints(&pc)
	printf(repr(pc) + '\n')
}
```
This code can be simplified by using the proposed *delegates* like this:
```
type PointCloud = struct {
        pts: [][3]real
}

fn (pc: ^PointCloud) add(p: [3]real) {
	pc.pts = append(pc.pts, p)
}

fn readPoints(onPoint: delegate fn (p: [3]real)) {
	for i := 0; i < 10; i++ {
		onPoint([3]real{i + 10, i + 20, i + 30})		
	}
}

fn main() {
	var pc: PointCloud
	readPoints(pc.add)        // Pass a method, not a structure
	printf(repr(pc) + '\n')
}
```
These delegates are actually syntactic sugar over interfaces, and `delegate fn` is internally just an `interface`. An `fn` can be implicitly converted to `delegate fn`, but not vice versa.

This seems to be significantly easier to implement than closures.

@marekmaskarinec @skejeton Do you find this feature useful?

**Comment by skejeton** [comment]
so `readPoints` will capture `pc` and use the method add? Sounds good. I'm personally not a fan of closures because it becomes hard to track what's captured, not as relevant in GC languages, but still a problem in for instance JS apps where closure prevents GC and it makes memory go up because you didn't unregister observers correctly.

By the way I think we can go around without delegate keyword at all, just make `object.method` use the object by itself if possible, because having the method address be bound to that particular object, when accessed as a member, only makes semantic sense. If people would want to get access to the method itself they could just do `Type.method`

**Comment by vtereshkov** [comment]
@skejeton Using the `delegate` keyword is not just a syntactic feature. An `fn` and a `delegate fn` will have different internal representations. An `fn` is a single 64-bit word containing the function entry point offset, while a `delegate fn` is an interface containing two words: the `self` pointer and the entry point offset. So I cannot pass a `delegate fn` where just an `fn` is expected.

An alternative solution is to make *all* functions occupy two words. However, that means that any function will have to be represented on the Umka VM stack as a pointer and dereferenced before use. This will impact all function calls, whereas only 1 % of functions will actually have this `self` pointer non-null.

**Comment by skejeton** [comment]
@vtereshkov My point is that semantically speaking no one would really to access `structure.function` to get the address to the `function`. They can already do that with a type, so it can be made so that `structure.function` would actually expand to a two-word instance with the self-pointer and the callback.

**Comment by vtereshkov** [comment]
@skejeton I agree. But you cannot pass this `structure.function` (two words) as an argument to a function that expects just a function (one word).

**Comment by skejeton** [comment]
@vtereshkov that is actually a good thing I think, if the user wants to pass callback that also alters 
some contexts that could be used for a nice way to handle cross cutting concerns. In my case at least I have `getPropertyLazy(name: str, ctx: interface{}, do: fn (ctx: interface{}): interface{}): interface{}`, where with implicit delegates it would be `getPropertyLazy(name: str,  fn (): interface{}): interface{}` which makes people able to pass an inline callback like this: `getPropertyLazy("name", fn (): interface{} { .... })`, or - if they need context, pass a delegate: `getPropertyLazy("name", derivedProperty.createProperty(...))`
Although implementation wise that means you need to handle the delegates and the callbacks as the same, which may be difficult if you want callback parameters to strictly occupy 8 bytes. It's actually a problem present in C++

**Comment by vtereshkov** [comment]
@skejeton Although you cannot convert a delegate into a function, you can convert a function into a delegate (with `self == null`). Your particular issue can be solved if you declare
```
getPropertyLazy(name: str, delegate fn (): interface{}): interface{}
```
and then call either 
```
getPropertyLazy("name", fn (): interface{} { .... })
```
or
```
getPropertyLazy("name", derivedProperty.createProperty)
```

**Comment by marekmaskarinec** [comment]
I don't think there's currently a place where I could use delegates. What I think might make them useful is adding literals. For example:

```
fn doSomething(struct{ x: int, y: int}{2, 4}.delegate(...) { ... })
```

This would allow us to effectively get rid of the usual `ctx` argument.

**Comment by vtereshkov** [comment]
@marekmaskarinec Good point. This is what I was thinking about too. If we're not allowed to write those delegate functions "in-place", they will be very cumbersome.

**Comment by vtereshkov** [comment]
No longer relevant.

**Comment by skejeton** [comment]
Context: #295
