### ISSUE TITLE
interface type switch-case

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#232]
In my code I often simulate discriminated unions like this:

```
if num := ^int(value); num != null {

} else if string := ^str(value); str != null {

} else {

}
```
And this is nice, but it happens quite frequently, that something like this would be desirable:
```
switch value {
  case int(num):
    // ...
  case str(string):
    // ...
  default:
    // ...
}
```
(where `value` is some interface)
it should also take reference if requested:
```
switch value {
  case int(num):
    // ...
  case ^str(string):
    // ...
  default:
    // ...
}
```
on `null`, `case null:` or `default:` will be handled if former is not present.

**Comment by marekmaskarinec** [comment]
> ```
> switch value {
>   case int(num):
>     // ...
>   case str(string):
>     // ...
>   default:
>     // ...
> }
> ```

Will `num` and `string` be variables storing the converted `value`? I like both
the feature and the syntax you sent. It could also make a lot of code faster
since all the checks could be offloaded to c.

**Comment by skejeton** [comment]
yes exactly

**Comment by vtereshkov** [comment]
This is a useful feature. Go also has "type switches". However,  I cannot agree with the proposed syntax. First, the statement begins exactly like a conventional switch and can be distinguished only by what follows the case labels, whereas the type switch semantics is completely different. Second, `int(num)` looks like casting `num` to `int`, which is not what it actually means.

I'd suggest this syntax instead:
```
switch v := type(value) {
    case int: {/* use v as int */}
    case str: {/* use v as str */}
    default: { /* ... */ }
}
```
