### ISSUE TITLE
[feature request] Builtin function 'assert'

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#240]
An 'assert' function that reports the file name, line number, the "string"yfied expression that failed and/or a user message would be useful.
Maybe also a compiler flag that removes the calls to 'assert' when set.

**Comment by vtereshkov** [comment]
@luauser32167 Do you expect it to be just syntactic sugar over `if (!cond) {error("Assertion failed: " + repr(x) + " is wrong")}`?

**Comment by luauser32167** [comment]
Yes, but if it could also support user messages, it would be even more useful. For example:
```
assert(!(0 <= idx && idx < len), sprintf("Index %d out of range 0..%d", idx, len));
=> "Assertion failed: !(0 <= idx && idx < len); Index -1 out of range 0 .. 10"
```
Not sure how useful it is to stringify the expression when a user message is provided.

**Comment by RobLoach** [comment]
You could implement your own assert.umka library :shrug: Would make it pretty easy to import when it was needed.

**Comment by vtereshkov** [comment]
Agree with @RobLoach.

**Comment by luauser32167** [comment]
Well, 'assert' cannot be implemented as a normal function because it needs to stringify its condition expression when it evaluates to false. In C it is a macro (uses the preprocessor):
```C
#ifdef NDEBUG
  #ifndef assert
    #define assert(e) ((void)0)
  #endif
#else
  #ifndef assert
    #define assert(e) ((e) ? (void)0 : _assert(#e, __FILE__, __LINE__))
  #endif
#endif
```

**Comment by marekmaskarinec** [comment]
The builtin `error` function will print a stack trace, which I think is enough.
