### ISSUE TITLE
Support compiling with 'tcc'

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#243]
[tcc](https://repo.or.cz/tinycc.git) compiles code much much faster (~10-30x) than 'gcc', 'clang' and 'msvc'. The 'Umka' code base
is very clean, but it doesn't compile with 'tcc', because 'tcc' is missing some functions.

I think these are the few functions which 'tcc' is missing in order to compile 'Umka':

```C
#if defined(__TINYC__) && defined(_WIN64)

#include <stdio.h> // sscanf
#include <stdarg.h> // va_list

#define strtoull _strtoui64

int
vsscanf(char const* s, char const* fmt, va_list args) {
  void* a[16];
  for (int i = 0; i < sizeof(a) / sizeof(a[0]); ++i) {
    a[i] = va_arg(args, void*);
  }
  return sscanf(s, fmt,
    a[0x0], a[0x1], a[0x2], a[0x3],
    a[0x4], a[0x5], a[0x6], a[0x7],
    a[0x8], a[0x9], a[0xA], a[0xB],
    a[0xC], a[0xD], a[0xE], a[0xF]
  );
}

int
vfscanf(FILE* f, char const* fmt, va_list args) {
  void* a[16];
  for (int i = 0; i < sizeof(a) / sizeof(a[0]); ++i) {
    a[i] = va_arg(args, void*);
  }
  return fscanf(f, fmt,
    a[0x0], a[0x1], a[0x2], a[0x3],
    a[0x4], a[0x5], a[0x6], a[0x7],
    a[0x8], a[0x9], a[0xA], a[0xB],
    a[0xC], a[0xD], a[0xE], a[0xF]
  );
}

#endif // if defined(__TINYC__) && defined(_WIN64)
```

**Comment by vtereshkov** [comment]
Does it mean that TCC does not support C99?

**Comment by luauser32167** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Tiny_C_Compiler) says that it implements most of [C99](https://en.wikipedia.org/wiki/C99) (including [variable-length arrays!](https://en.wikipedia.org/wiki/Variable-length_array)). Maybe complex numbers are missing but I don't think Umka uses complex numbers math anyway.

**Comment by vtereshkov** [comment]
So why are these functions missing? They are part of the C99 standard: https://en.cppreference.com/w/c/io/vfscanf. Moreover, I see their prototypes in the TCC repo: https://repo.or.cz/tinycc.git/blob/HEAD:/win32/include/stdio.h. Is anything wrong with the TCC build or the standard library it is linked against?

**Comment by luauser32167** [comment]
I was wrong. It's not 'tcc' itself that is missing the functions, but the C runtime library ('msvcrt.dll'), that it links to.

**Comment by vtereshkov** [comment]
You are right that `msvcrt.dll` doesn't export these functions. However, it's up to the compiler to decide how to support them in order to be C99-compliant. For example, MinGW implements them itself:

https://github.com/mirror/mingw-w64/blob/22a065d89f9996839a78c0276248fa3e0113db51/mingw-w64-crt/stdio/mingw_vfscanf.c#L1624

I don't know why TCC doesn't do that, but I think it's not an Umka issue to fix a specific compiler incompleteness.

**Comment by luauser32167** [comment]
Sure, but a small workaround on Umka's part would enable it to be compilable with the fastest C compiler (as far as I know).
You could also use a simpler function than 'strtoull'  (I think Umka only calls it with base=10), or just copy it from [mingw](https://github.com/mirror/mingw-w64/blob/22a065d89f9996839a78c0276248fa3e0113db51/mingw-w64-crt/misc/strtoumax.c).
