### ISSUE TITLE
Map key becomes "valid/existing" after value lookup

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#247]
```Go
fn main() {
  m := map[int]str{};
  printf("%d\n", int(validkey(m, 69105))); // not valid
  var s: str = m[69105];
  printf("%d\n", int(validkey(m, 69105))); // but now valid
}
```

**Comment by vtereshkov** [comment]
@luauser32167 This is the intended behavior, similar to that of `std::map` in C++. It is discussed in detail in 

https://github.com/vtereshkov/umka-lang/issues/170

**Comment by luauser32167** [comment]
This is a bit surprising...
Have you considered the approach that ['stb/ds.h'](https://github.com/nothings/stb/blob/master/stb_ds.h#L241)  uses for its hashmaps? It has a setter function which sets the "default value" for the hashmap. When a key is used for lookup with the function 'hmget', and it isn't found, the value of the default item is returned.

Basically it has the following semantics:
```Go
  m1 := map[int]str;
  printf("%s\n", m1[69105]); // "" (empty string, because the default value is zero initialized)
  mapsetdefault(m1, "leaves");
  printf("%s\n", m1[69105]); // "leaves"
  printf("%s\n", repr(m1)); // { } (no keys)

  type Point = struct { x, y: int };
  m2 := map[str]Point;
  m2["origin"].x = 10; // sets the default value's 'x' field to 10 (because the key "origin" was not found)
  printf("%s\n", repr(m2)); // { } (no keys)
  m2["origin"] = Point{10, 20};
  printf("%s\n", repr(m2)); // { "origin": Point{x: 10, y: 20} } (now has 1 key called "origin")
  printf("%d\n", mapgetdefalut(m2).x); // the default value's 'x' field is still 10
```

**Comment by vtereshkov** [comment]
@luauser32167 The following is even more surprising for me than having `m2["origin"]` initialized on first access:
```
m2["origin"].x = 10; // sets the default value's 'x' field to 10 (because the key "origin" was not found)
printf("%s\n", repr(m2)); // { } (no keys)
```
Assigning `m2["origin"].x = 10` is a clear indication that I want `m2["origin"]` to exist. But `m2` is still empty. That's weird.
