### ISSUE TITLE
Allow omitting types in "full" variable declarations when they can be inferred

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#250]
The 'var' token is the declarator token that my eyes scan for when looking for variable declarations. The problem is that it cannot be used when using the ':=' operator (declaration and initialization with type inference), which requires writing the type 2 times.

```Go
fn main() {
  var a: int = 1;
  // var b := 2; // currently not allowed
  c := 3; // without the 'var' token, it kind of looks like an assignment and not like a variable declaration with initialization
  var d: int = 4; // for "simple types" like 'int' it's not a problem...
  var e: map[int]str = map[int]str{}; // but for structured types the type needs to be written 2 times

  // in 'for' loops, the 'var' keyword wouldn't really be necessary because it is preceded by the 'for' keyword
  // for var it := MyIterator(...); !it.done(); it.advance() {
  //   ...
  // }
}
```

**Comment by vtereshkov** [comment]
@luauser32167 The `:=` operator is, by definition, a short variable declaration, as opposed to `=` used for assignment. Thus, writing `var b := 2` is unnecessarily redundant. The only enhancement I can consider is to allow omitting types in the "full" declarations when they can be inferred, e.g., `var b = 2`.

**Comment by luauser32167** [comment]
I think always having the ```:``` in variable declarations, even if redundant, is more consistent.

```Go
var a : int = 1; // The type goes between ':' and '='.
var b := 2; // There is no type between ':' and '=', i.e we want the type to be inferred.

var c = 3; // There is no type between '=' and the variable name, i.e we want the type to be inferred.
var d int = 4; // The type goes between the variable name and '='.
```
