### ISSUE TITLE
The interpreter removes whitespace characters from paths/filenames

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#252]
```cmd
$ umka "./filename with whitespace.um"
Error: Cannot open file path/to/filenamewithwhitespace.um
```

**Comment by vtereshkov** [comment]
@luauser32167 I think Umka will not support spaces in file names, as those file names are often used in qualified identifiers. However, it should produce a readable error message.

**Comment by dnm** [comment]
Does this extend to pathnames in general, e.g., (on Windows) "`C:\Users\John Doe\Hack\Umka\script.um`"?

**Comment by vtereshkov** [comment]
@dnm For now, I'd say this is _not_ intended. In other words, I'd like Umka to work with folder names that have spaces. However, I should carefully think of how this may interfere with the path regularization (i.e., converting `./` and `../` into an absolute path).

Please disregard Umka 0.6. It was a total mess with module import paths. The current whitespace issue is definitely a lesser evil.

**Comment by dnm** [comment]
@vtereshkov Understood, thanks for clarifying.

**Comment by vtereshkov** [comment]
Now whitespace is allowed in folder names, though not in module names. 

Thanks, @marekmaskarinec
