### ISSUE TITLE
Multiplatform UMI modules

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#254]
It would be useful if one could ship UMI modules like this:

```
my_mod.um
my_mod_linux.umi
my_mod_windows.umi
```

This would provide two versions - one for windows and one for linux.

**Comment by vtereshkov** [comment]
@marekmaskarinec Do you mean automatically searching for `*_linux.umi` or `*_windows.umi` depending on the OS? A good idea. If not found, Umka should still search for just `*.umi`.

**Comment by vtereshkov** [comment]
@marekmaskarinec Done. Please check it.

**Comment by marekmaskarinec** [comment]
Works for me on linux.
