### ISSUE TITLE
Proposal: `new` taking a value as an argument

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#266]
Right now one needs to do:
```
	tr.schedule = new(rail.Schedule)
	tr.schedule ^= getSchedule(this, map[str]any(m["schedule"]))
```

I think this could be shortened to:
```
	tr.schedule = new(getSchedule(this, map[str]any(m["schedule"])))
```

The old type based way should obviously stay.

**Comment by vtereshkov** [comment]
@marekmaskarinec Unfortunately, the syntax you propose is quite difficult to parse. Namely, it requires an infinite lookahead to distinguish between a type and an expression, as the expression may be a type cast and therefore begin with a type. Here is an example:
```
p := new([2][2][2][2][2][2][2][2][2][2]int)      // Old form of new() with a type
p := new([2][2][2][2][2][2][2][2][2][2]int(5))   // New form of new() with an expression
```
Without rewriting the parser, I can only propose a more cumbersome syntax with an explicit type: `fn new(T [, expr: T]): ^T`. Thus, you would have to write
```
tr.schedule = new(rail.Schedule, map[str]any(m["schedule"]))
```
However, from some perspective, this form is even better. When looking at it, the reader will never have to guess whether `rail.Schedule` is a type or a variable.

**Comment by marekmaskarinec** [comment]
Another variant would be a new function, for example `alloc`.

```
tr.schedule = alloc(getSchedule(this, map[str]any(m["schedule"])))
```

**Comment by vtereshkov** [comment]
@marekmaskarinec Implemented as `fn new(T [, expr: T]): ^T`.
