### ISSUE TITLE
Optimize string element access

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#273]
Taking `s[i]` is `O(len(s))` now, as it requires checking the string bounds with `strlen(s)`. For example:
```
import "std.um"

fn main() {
	s := ""
	for i := 0; i < 100000; i++ {
		s += "abracadabra"
	}

	l := len(s)
	cnt := 0

	start := std.clock()

	for i := 0; i < l - 1; i++ {
		if s[i] == s[i + 1] {
			cnt++
		}
	}

	stop := std.clock()

	printf(repr(stop - start) + '\n') // 186.463000
}
```
Fixing this issue probably means redesigning the internal representation of a string, so that it could store its length and capacity, just like in a dynamic array. But how to keep strings compatible with C?

**Comment by luauser32167** [comment]
> Fixing this issue probably means redesigning the internal representation of a string, so that it could store its length and capacity, just like in a dynamic array. But how to keep strings compatible with C?

I think that in C string literals, stack 'char' buffers, and pointers returned by 'malloc' and 'realloc' have a guaranteed alignment of 8 or 16?, which leaves their lowest 3 or 4 bits to be always unset. One of these bits could be used as a flag to indicate that this pointer points to a 'umka-string' which knows its 'capacity', 'length' and other implementation specific fields perhaps. These fields can be stored before the first character that the pointer points to, exactly like [ansistrings](https://wiki.freepascal.org/Ansistring) are implemented in 'freepascal'.

**Comment by vtereshkov** [comment]
@luauser32167 

> ... this pointer points to a 'umka-string' which knows its 'capacity', 'length' and other implementation specific fields perhaps. These fields can be stored before the first character that the pointer points to.

This is what I intend to do. Moreover, if I retain the terminating null character, the Umka string will still be compatible with C (but not vice versa).

> I think that in C string literals, stack 'char' buffers, and pointers returned by 'malloc' and 'realloc' have a guaranteed alignment of 8 or 16?, which leaves their lowest 3 or 4 bits to be always unset. One of these bits could be used as a flag...

An interesting observation. Something like the "NaN boxing". However, even if it's true, I don't want to rely on these implementation details not guaranteed by the C standard. And it will definitely complicate the string usage, since the `char` pointers will no longer be pointers in the proper sense.

My idea was just to have all `str`s pointing to Umka strings. Maybe it will also require an Umka API function to construct an Umka string in C code.

But this is a big change that I postpone until at least Umka 1.1. In Umka 1.0, I'll have only the string length cache. In the code example above, it provides a 2000x speedup.
