### ISSUE TITLE
Inconsistent weak pointer semantics

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#274]
A weak pointer to a heap frame is OK, but to a stack frame is not. However, deciding whether a function frame must escape to heap is compiler's internal logic not revealed to the user. So this behavior is non-deterministic from the user's standpoint.
```
fn f(): int {
        p := new(int)
        a := 42
        return ^int(weak ^int(&a))^   // 42       
}

fn g(): int {
        a := 42
        return ^int(weak ^int(&a))^   // Runtime error: Pointer is null         
}

fn main() {
        printf(repr(f()) + '\n')
        printf(repr(g()) + '\n')
}
```

**Comment by marekmaskarinec** [comment]
Is anything stopping us from making weak pointers to stack objects, or is this just an incorrect runtime error?

**Comment by vtereshkov** [comment]
@marekmaskarinec To use a weak pointer, we should first ensure that it is pointing to an existing object, i.e., an object that has not been deleted *or replaced with another object at the same address*. I don't know how to perform this check for a stack pointer. For a heap pointer it's much easier to do. The weak pointer is a pair of integers: the unique ID of the heap page and the offset within the page. Even if the page has been removed and some other page allocated at the same address, it would have a different ID, so the weak pointer would no longer be valid.

**Comment by vtereshkov** [comment]
After eliminating the stack frame escape logic, the original problem is gone. However, a new problem is possible:
```
fn f(): weak ^int {
        a := 42
        return weak ^int(&a)
}

fn g() {
        a := 666         
}

fn main() {
        p := f()
        g()
        a := ^int(p)^
        printf(repr(a) + '\n')    // 666
}
```
