### ISSUE TITLE
Init with string

### ISSUE THREAD

**Issue by skaller** [vtereshkov/umka-lang#28]
The existing `umkaInit` function takes a string naming a file.

This is useful only for testing correctness of umka, it is of no use for the
primary purpose of the product, namely as an embedded scripting language
which can interact with a C environment.

So I propose to add a function that accepts a `char const *` which is an NTBS containing
the text of an Umka script. 

A decision must be made on the ownership of the string and *documented*.
If the caller retains ownership, the lifetime must be specified.
Otherwise if ownership is passed to the called function, the allocation method the client
must use (eg `malloc()`) must be specified.

I think, although not at all sure, that the client should retain ownership, because
a common case would be to pass a string literal, which is likely in static storage
and cannot be deleted.

**Comment by vtereshkov** [comment]
Already done. See [here](https://github.com/vtereshkov/umka-lang/blob/master/spec.md#api-functions). The string is copied to the lexer's internal buffer during initialization.

**Comment by skaller** [comment]
Ah ok sorry. Cool!
