### ISSUE TITLE
Passing parameters from C to Umka

### ISSUE THREAD

**Issue by skaller** [vtereshkov/umka-lang#29]
A procedure is a function that does not return a value, a return of `void` is used in C.
Do Umka functions always return a value?

If so, what component of UmkaStackSlot will be filled, and by what value?

If a function has no return value can a NULL be passed as the address of the slot to hold the return value (implying no value is stored).

I guess also when calling a function with no arguments, a NULL can be given as the address of the parameter array, since the count of boxes is specified as 0,  is this correct?

Just clarifying boundary cases (since Felix has a very strict type system and I want the types to match the API semantics accurately if possible)

**Comment by vtereshkov** [comment]
- If a function has no parameters, a `NULL` can be passed as `params`, like [here](https://github.com/vtereshkov/umka-lang/blob/master/examples/3dcam.c#L96).
- If a function has no return value (or the returned type is `void`), a `NULL` can be passed as `result` (ibid.).
- If a function has no structured parameters or all structured parameters are passed by reference, the number of parameter stack slots is equal to the number of parameters, like here:

```
                    fn update(t: real, pos, vel, att: ^mat.Vec): real {...}
```
```
                    UmkaStackSlot param[] = {
                                             {.ptrVal  = (int64_t)&att},
                                             {.ptrVal  = (int64_t)&vel},
                                             {.ptrVal  = (int64_t)&pos},
                                             {.realVal = t}};
                    UmkaStackSlot result = {0};

                    if (!umkaCall(umka, umkaGetFunc(umka, NULL, "update"), sizeof(param) / sizeof(param[0]), param, &result))
                    {
                        UmkaError error;
                        umkaGetError(umka, &error);
                        printf("\nUmka runtime error %s (%d): %s\n", error.fileName, error.line, error.msg);
                        break;
                    }

                   ctrl = result.realVal; 
```

**Comment by skaller** [comment]
Excellent, thank you! Consider adding these comments to specs. Boundary conditions/border line case should always be spelled out IMHO, even if implied by more general rules. The representation seems consistent!
