### ISSUE TITLE
Improve error messages for a newline or comma before the closing brace

### ISSUE THREAD

**Issue by judah-caruso** [vtereshkov/umka-lang#292]
When constructing a compound literal (array/struct), placing the closing `}` on a new line causes this error due to auto semicolon insertion:

```
arr := []int{
    1, 2, 3, 4
}

// } expected but ; found
```

Trailing commas output a different error:
```
vec := Vector3{
    x: 10,
    y: 20,
    z: 30,
}

// Unknown field 
```

**Comment by judah-caruso** [comment]
From reading around, I take it both errors are to be expected. I would argue the error messages for these specific situations could be improved, however.

**Comment by vtereshkov** [comment]
@judah-caruso Yes, this is a consequence of the implicit semicolon rule. This issue duplicates #58 and #96. However, I agree we need better error messages.
