### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by gvtret** [vtereshkov/umka-lang#3]
Hi there!
Is it possible to add compare benchmarks for Umka, Wren.io, Lua?
Two suits:
* calling C function from script.
* calling sript function from C.
Like this: http://wren.io/performance.html

**Comment by vtereshkov** [comment]
That's what I currently [have](https://github.com/vtereshkov/umka-lang#performance).

**Comment by gvtret** [comment]
Thanks!
