### ISSUE TITLE
case no longer works with char literal expressions?

### ISSUE THREAD

**Issue by dnm** [vtereshkov/umka-lang#304]
This is more of a question than anything else (i.e., I don't think this is an _issue_ per se; it might be, but I haven't done enough digging into the various relevant things to feel comfortable positioning it as such; "I haven't done my homework" [or at least not enough of it, yet]).

Previously, something like

```
for cmd in input {
    switch cmd {
        case 'a': acc++
        case 'b': acc--
    }
}
```

worked (where `acc` was previously declared as "`var acc: int = 0`", and `input` is something like "`input := getIn()`"; `getIn()` returns `str`).

In Umka 1.2, I get "Incompatible types int and char". I've tried various ways of fixing this, but I've not yet hit on the obvious Right Thing I should be doing.

**Comment by vtereshkov** [comment]
@dnm It looks like that you're again comparing 1.2 to some very old version. The `for..in` statement now involves a _mandatory_ index variable and an _optional_ item variable. See the [language reference](https://github.com/vtereshkov/umka-lang/blob/master/doc/lang.md#the-forin-statement).

So your loop should be something like
```
for i, cmd in input {
    switch cmd {
        case 'a': acc++
        case 'b': acc--
    }
}
```

**Comment by dnm** [comment]
@vtereshkov Ah, OK. I hadn't even thought to consult the reference on the `for..in` statement (at least, I hadn't yet worked my way back to there yet), so the pointer (no pun intended) is appreciated. And yes, your intuition is correct; I originally wrote the code in question for Umka 0.6.

**Comment by vtereshkov** [comment]
@dnm I didn't know Umka had users other than the [tophat](https://tophat2d.dev/) developers :-) So I discussed this breaking change only with them, and they approved it.

**Comment by dnm** [comment]
@vtereshkov Well, I suppose I _technically_ qualify as a user, but I'm not sure I'd necessarily describe myself as such in the generally accepted sense, and certainly not anywhere near as important in terms of my usage as the [tophat](https://tophat2d.dev/) devs, to be sure. :) Probably more accurate to say I'm an Umka tinkerer, perhaps.

My primary public prior work in Umka 0.6 was just a quick & dirty implementation of [Deadfish](https://esolangs.org/wiki/Deadfish#Umka). Having checked in on Umka again recently and having seen the 1.2 release and the work done generally on the language since I last checked, I figured I'd update my code (if needed) to work on 1.2.

I certainly don't have any issues with the change to `for..in`, I'm just bringing myself back up to speed with all the new language changes & features. Thanks again for bearing with me!
