### ISSUE TITLE
expose `stdin` and `stdout`

### ISSUE THREAD

**Issue by thacuber2a03** [vtereshkov/umka-lang#324]
they are really useful in standalone command line applications for things like piping, and the `*scanf` family of functions do a good job at taking interactive input, but don't work with this sort of thing
they could possibly be in `std.um` as that's where the rest of the file functionality is stored in

**Comment by vtereshkov** [comment]
Done. 

Piping example:
```
// test.um
import "std.um"

fn main() {
	a := make([]char, 100000)
	std.fread(std.stdin(), &a)
	std.fwrite(std.stdout(), []char("PATH = " + str(a)))
}
```
```
C:\Users\vtere\Desktop\umka-lang\umka_windows_mingw>echo %path% | umka.exe ..\test.um
PATH = C:\emsdk;C:\emsdk\upstream\emscripten;C:\emsdk\node\14.18.2_64bit\bin;...
```

**Comment by vtereshkov** [comment]
@thacuber2a03 In Umka, you can assign to any variable (that's why they are called variables). There is no such concept as non-assignable variables, because I cannot imagine many use cases for them. So `stdin` etc. can be either constants or functions.

**Comment by thacuber2a03** [comment]
I meant, like, in most programming languages you can't change the variables of another module without exporting them
and speaking of constants, can't the file pointers just be that then?

**Comment by vtereshkov** [comment]
> in most programming languages you can't change the variables of another module without exporting them

Of course you cannot. But then you cannot see them from other modules either. If you need `stdin`, you have to export it from `std.um`, but then you can re-assign it too.

**Comment by thacuber2a03** [comment]
@vtereshkov well, what about making them constants then?
