### ISSUE TITLE
how do I return an interface type?

### ISSUE THREAD

**Issue by thacuber2a03** [vtereshkov/umka-lang#326]
I'm writing an Umka interpreter for [Mal (Make-A-Lisp)](https://github.com/kanaka/mal) and I want to return an interface type (a `MalVal`) for `read_form` in Step 1: Read and Print.

so far, for `read_form` I've written this:
```um
fn read_form(reader: Reader): types.MalVal {
	// todo
	return types.MalNumber { 0 }
}
```
and in `types.um` I have:
```um
type MalType* = uint8

const (
	MAL_LIST* = 0
	MAL_SYMBOL*
	MAL_NUMBER*
	MAL_KEYWORD*
)

type MalVal* = interface {
	getType(): MalType
}

type MalList* = struct { values: []MalVal }
fn (l: ^MalList) getType(): MalType { return MAL_LIST }

type MalNumber* = struct { number: real32 }
fn (n: ^MalNumber) getType(): MalType { return MAL_NUMBER }

type MalSymbol* = struct { symbol: str; isKeyword: bool }
fn (s: ^MalSymbol) getType(): MalType {
	if s.isKeyword { return MAL_KEYWORD }
	return MAL_SYMBOL
}
```
but when I try to run the code with the above signature for `read_form`, this error triggers:
```
Error /home/thacuber2a03/Documentos/gitclones/mal/impls/umka/reader.um (86, 12): Method getType is not implemented
```
which points exactly at the return statement in `read_form`, and, intuitively, makes no sense, as every Mal type I've made has a `getType` method assigned to it.
am I doing something wrong?

**Comment by vtereshkov** [comment]
@thacuber2a03 The method should be exported in order to be visible from other modules:
```
fn (n: ^MalNumber) getType*(): MalType { return MAL_NUMBER }
```

**Comment by thacuber2a03** [comment]
@vtereshkov that's hilarious, thanks anyways
