### ISSUE TITLE
Allow variable redeclaration from multiple return function call

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#329]
Example:

```
a, err := something()
if err != null ...

b, err := somethingElse()
if err != null ...
```

Go allows this behavior:

> Unlike regular variable declarations, a short variable declaration may redeclare variables provided they were originally declared earlier in the same block (or the parameter lists if the block is the function body) with the same type, and at least one of the non-blank variables is new. As a consequence, redeclaration can only appear in a multi-variable short declaration. Redeclaration does not introduce a new variable; it just assigns a new value to the original.

**Comment by vtereshkov** [comment]
Done. This example is now valid:
```
type Err = any

fn something(): (int, ^Err) {
        return 42, new(Err, []int{4, 5})
}

fn somethingElse(): (str, ^Err) {
        return "Hello", new(Err, "World")
}

fn main() {
        a, err := something()
        if err != null {
                printf("%v %v\n", a, err^)  // 42 [4 5]
        }

        b, err := somethingElse()
        if err != null {
                printf("%v %v\n", b, err^)  // "Hello" "World"
        }
}
```
