### ISSUE TITLE
Calling an Umka function from C

### ISSUE THREAD

**Issue by thacuber2a03** [vtereshkov/umka-lang#332]
I was embedding Umka in a small project, and I thought about passing an Umka function pointer to a C external func so that the C function called the Umka function to report an error, but I didn't see any intuitive way of doing so. is it even possible?

**Comment by marekmaskarinec** [comment]
Currently it's not possible. See this issue: https://github.com/vtereshkov/umka-lang/issues/248

**Comment by vtereshkov** [comment]
Yes, this is the same issue. I'd close this one as duplicate.

**Comment by thacuber2a03** [comment]
oh, ok, sorry, didn't know it was already known
