### ISSUE TITLE
Accessing Umka API without linking against Umka

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#333]
**Proposal:**

1. Keep the current "static" API intact for backward compatibility. E.g.,
```
char *s = umkaMakeStr(umka, "Hello");
```
2. Add, as an option, a new "dynamic" API accessible through the Umka instance. E.g.,
```
UmkaAPI *api = umkaGetAPI(umka);
char *s = api->umkaMakeStr(umka, "Hello");
```
This "dynamic" API can be recommended for UMIs to avoid linking them against `libumka.dll`/`libumka.so`.

**Comment by skejeton** [comment]
where is umkaGetApi defined?

**Comment by vtereshkov** [comment]
@skejeton It's an inlined function defined in `umka_api.h`.
