### ISSUE TITLE
Parsing expressions using an operator precedence table instead of recursive decent

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#335]
The current expression parsing code is a bit long (using recursive decent for resolving the operators' precedence) and is taking many function calls to parse a single integer literal:
```
parseExpr
  parseLogicalExpr
    parseLogicalTerm
      parseRelation
        parseRelationTerm
          parseTerm
            parseFactor
              TOK_INTNUMBER
```

There's a simpler/more compact/efficient way of parsing expressions called "Pratt parsing". Here are some sources that talk about it/explain it.

[Making a calculator from scratch - #SoME3](https://www.youtube.com/watch?v=myZcNjKcVGw)
[Discussion with Casey Muratori about how easy precedence is...](https://m.twitch.tv/videos/2024681994)
[Pratt's original paper](https://tdop.github.io) -- hard to understand, in my opinion

You can see it being used in Lua here: [Lua's operator precedence table](https://github.com/lua/lua/blob/7923dbbf72da303ca1cca17efd24725668992f15/lparser.c#L1237)

Would rewriting the parser result in a measurable speedup? For huge tables of integers/constants, maybe, otherwise probably not. It would reduce the number of lines of code, for sure though.

**Comment by vtereshkov** [comment]
I'm not sure it can have any effect, even in terms of lines of code: parsing is interleaved with code generation, which is not uniform (`a && b` differs much from `a & b`), the ternary operator probably needs a special treatment, etc.

**Comment by luauser32167** [comment]
@vtereshkov [here](https://gist.github.com/luauser32167/650b1081fbee3715025af2fa8ed54478) is a modified ```umka_expr.c``` that has a ```#define USE_RECURSIVE_DESCENT_EXPRESSION_PARSER``` to switch from the current recursive descent expression parser to a pratt expression parser. It seems to produce the same output (diffing ```tests\expected.log```), but that doesn't mean that it is correct :^).
