### ISSUE TITLE
Listing multiple parameters of the same type in function signatures

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#339]
Right now it is allowed to list multiple names in a variable declaration:
```
var a, b: int;
```
but this shortcut does not work for function parameters.

```
fn f(xs: []int, a: int, b: int): int {
  return xs[a] + xs[b];
}
// =>
fn f(xs: []int, a, b: int): int {
  return xs[a] + xs[b];
}
```

This would probably also require ';' as a parameter separator (like in Pascal), otherwise it might get confusing.

**Comment by vtereshkov** [comment]
@luauser32167 I don't understand the problem. Grouping multiple parameters of the same type has been allowed in Umka since the beginning:
```
fn f(xs: []int, a, b: int): int {
  return xs[a] + xs[b]
}

fn main() {
        printf("%v\n", f({4, 6, 7}, 1, 2)) // 13
}
```
It uses a comma rather than a semicolon.

**Comment by luauser32167** [comment]
Ooops, I thought I tested this. Sorry my bad.
