### ISSUE TITLE
Poor instruction sequence generation for the short-circuiting operators '&&' and '||'

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#343]
The following code

```
var a, b, c, d: bool;
var v: int;
if a && b && c && d {
  v = 69;
} else {
  v = 105;
}
```

generates less efficient instructions sequence than

```
var a, b, c, d, e: bool;
var v: int;
e = false;
if a { if b { if c { if d {
  e = true;
} } } }
if e {
  v = 69;
} else {
  v = 105;
}
```

Similarly for the logical or operator ('||'), the following

```
var a, b, c, d: bool;
var v: int;
if a || b || c || d {
  v = 69;
} else {
  v = 105;
}
```

generates less efficient instructions sequence than

```
var a, b, c, d, e: bool;
var v: int;
e  = true;
for true {
  if a { break; }
  if b { break; }
  if c { break; }
  if d { break; }
  e = false; break;
}
if e {
  v = 69;
} else {
  v = 105;
}
```

Also the instruction sequence for the ```switch``` statement seems to do unnecessary equality evaluations.

**Comment by vtereshkov** [comment]
Optimized `&&` and `||`. Minus 500 instructions out of 50000 in a typical game project. However, 
* All optimizations are pairwise. No special optimizations for chained `&&` or `||`
* No special optimizations for the `if` statement condition
