### ISSUE TITLE
What does 'Umka' mean/stand-for?

### ISSUE THREAD

**Issue by ktbarrett** [vtereshkov/umka-lang#35]
This might not be the most important question in the world :^) Google tells me it's an anglicization of Умка a suburb of Belgrade, but I'm not getting anything else. I'm curious.

**Comment by vtereshkov** [comment]
@ktbarrett The language is named after my girlfriend's cat, who, in turn, was named after a fictional polar bear from an [old Soviet cartoon](https://en.wikipedia.org/wiki/Umka_(1969_film)). The word *umka* literally means a polar bear in the Chukchi language.
