### ISSUE TITLE
Infinite loop prevention

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#352]
It seems that, currently, there is no way to stop the umka vm when it gets caught in an infinite loop. Perhaps a notion of maximum number of opcodes allowed, or maximum number of seconds allowed, per ```umkaCall```, after which the execution of the function is stopped.

**Comment by vtereshkov** [comment]
@luauser32167 What use cases do you know? For me, an infinite loop should be infinite. If it's a programmer's mistake, the program can be terminated with Ctrl + C.

**Comment by luauser32167** [comment]
A graphical application that allows scripting but doesn't want to hang because of some rogue script.

Example: A bulk rename program that previews how file names are going to change before making the changes to the file system. Uses scripting to control how the renaming is performed. (I think there's such a program already that uses javascript or some other scripting language)

**Comment by vtereshkov** [comment]
Doesn't seem very useful for any known use cases.

**Comment by luauser32167** [comment]
> Doesn't seem very useful for any known use cases.

A game developer wants to enable players to write their own scripts for it. They (the game developer) would not want the game to hang just because the players have made a mistake and wrote an infinite loop. The game developer would probably prefer to present an error message that some function took too long to run which would suggest a scripting error, or inform the players of a way to increase the time/instructions allowed for the execution of the function.
