### ISSUE TITLE
Playground: The stdout isn't cleared between runs if no new line was added

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#359]
run
```
fn main() {
  printf("Hello, ")
}
```
then
```
fn main() {
  printf("World!\n");
}
```
you'll see `Hello, World!`

**Comment by vtereshkov** [comment]
In fact, there are two problems:

1. The `stdout` isn't cleared on clicking `Run`. It's easy to fix.
2. Nothing is printed to the `stdout` before a new line character is entered. To my knowledge, this is the Emscripten's default behavior. Not sure if we can do anything with it.

**Comment by vtereshkov** [comment]
Fixed.
