### ISSUE TITLE
`std.freadall` encounters a premature EOF error when reading files without "b" flag.

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#367]
If you open a file with "rb" flag, it works just fine since the length of the file matches the output, but if you use "r" flag, it will not work because without "b" (binary mode), it will convert `\n` to `\r\n` on Windows.

**Comment by vtereshkov** [comment]
It was supposed to be used with `"rb"` only. 

Not even sure about the behavior of C's `fread()` with `"r"`.

**Comment by skejeton** [comment]
It should probably throw an error if it's only intended to work with "rb"

**Comment by vtereshkov** [comment]
I see `freadall()` doesn't crash but just returns the `.eof` error. I think this is acceptable, except that I should have mentioned the `"rb"` mode requirement in the docs. The docs are now fixed.
