### ISSUE TITLE
std.clock() return values are weird.

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#39]
The values given don't seem to make any sense.

**Comment by vtereshkov** [comment]
@marekmaskarinec Can you give an example?

**Comment by marekmaskarinec** [comment]
When I run std.clock() and std.time() in comparison, clock doesn't seem to increment in seconds. Am I supposed to divide by it something like in c?

**Comment by vtereshkov** [comment]
@marekmaskarinec It is already divided:

https://github.com/vtereshkov/umka-lang/blob/b6ea369b494bf5240d8220852afe16f384ddca50/src/umka_runtime.c#L77

So I cannot understand what is wrong with it. A concrete example would help. By the way, if you run the raytracer example, do you see the correct rendering time estimate in the end? Or it is total garbage?

**Comment by marekmaskarinec** [comment]
Yes. The number produced by raytracer seems real. When I run use it in my project, it is weird.
![clockstuff](https://user-images.githubusercontent.com/42782325/110854659-90810c80-82b5-11eb-845b-ed7573453d41.gif)

**Comment by vtereshkov** [comment]
@marekmaskarinec  Yes, I've just cloned your repo and seen the same effect. While I'm investigating it, could you please try the `master` branch of Umka (with corresponding `import/*.um`, of course)?

**Comment by vtereshkov** [comment]
By the way, to avoid memory leaks reported by Umka, you can explicitly call the empty `fn main() {}` from your C/C++ program just before terminating it.

**Comment by marekmaskarinec** [comment]
Oh. I can ditch the game function and use only main. That would probably be even better.

**Comment by vtereshkov** [comment]
Probably you are right. But please keep in mind that after returning from `main()` Umka calls global garbage collection, so you will not be able to call any other Umka functions.

**Comment by marekmaskarinec** [comment]
I'm not worried about that.

Do you have any idea about the clock issue?

**Comment by vtereshkov** [comment]
Not yet. Probably I'll first try dynamic linking with the `libumka.so` from `master`.

**Comment by marekmaskarinec** [comment]
I link it statically.

**Comment by vtereshkov** [comment]
I think the reason is that you don't limit the frame rate. When I limit it to, say, 20 FPS, everything runs fine and `clock()` produces correct values. That's what I do:
```
	...
	prevclock := 0.0

	for true {
		curclock := std.clock()
		
		if (curclock - prevclock > 0.05) {
			prevclock = curclock

			printf(repr(std.time()) + repr(std.clock()) + '\n')

			// performs important stuff in engine
			tophat.cycle(&w, &h, 0xffffffff, cam)

		...
		}
	}
```

**Comment by marekmaskarinec** [comment]
I will try limiting it. Although this isn't a good way to do this, since tophat.cycle takes some time too. Swap buffers should have some framerate limiter though.

**Comment by vtereshkov** [comment]
I cannot say for sure, but if `clock()` is based on counting CPU cycles and the CPU load is about 100 %, it's hard to say _what_ cycles it actually counts.

**Comment by marekmaskarinec** [comment]
Cpu load is about 2 % with the game. I think opengl limits the frames already.

**Comment by vtereshkov** [comment]
It's curious that when I call `clock()` directly from C, I see exactly the same problem:
```
void umCNFGSwapBuffers(UmkaStackSlot *p, UmkaStackSlot *r) {
	CNFGSwapBuffers();
	printf("%d %f\n", time(NULL), (double)clock() / CLOCKS_PER_SEC);
}
```

**Comment by marekmaskarinec** [comment]
This is weird. I will try experimenting a bit with it.

**Comment by marekmaskarinec** [comment]
The value seems to be dependant on the cycle speed.

**Comment by Mazdaywik** [comment]
Function `clock()` on Linux measures CPU time of a process. If the process waits for I/O, other process created by `system()` or even `sleep()`/`usleep()`, function `clock()` this idle intervals don’t account. But function `time()` measures wall-clock time. And then sum `time() + clock() / CLOCKS_PER_SEC` on Linux is not constant (but is constant on Windows).

If you want precise wall-clock time on Linux, use `clock_gettime()` with `CLOCK_REALTIME`:

<https://www.opennet.ru/man.shtml?topic=clock_gettime&category=3>

Note: standard C function `clock()` may be implemented as wrapper for `clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &tp)`.

**Comment by vtereshkov** [comment]
@Mazdaywik Yes, this is roughly what I have expected. But `clock_gettime()` is unavailable on Windows, so I'll have to use platform-specific `#define`s.

**Comment by vtereshkov** [comment]
I close the issue, though I still have doubts regarding the availability of `clock_gettime()` on macOS:

https://stackoverflow.com/questions/41509505/clock-gettime-on-macos
