### ISSUE TITLE
Memory leak when the last array ref is an item ref

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#41]
This code causes a memory leak:
```
type ent = []int	

fn main() {
	var s: ^ent
	t := []ent{}
	
	for i := 0; i < 3; i++ {
		t = append(t, []int{7})
		s = &t[0]
	}
}
```
A shorter example without `append()`:
```
var p: ^^int

fn main() {
	a := []^int{new(int), new(int)}
	p = &a[1]
}
```

**Comment by vtereshkov** [comment]
The possible origin is as follows:
* Dynamic array items' ref counts are decremented only before removing the last remaining array ref
* The last remaining ref to the old `t` after `append()` is the item ref `s`
* This ref is removed as an item ref, not an array ref, so the other items' ref counts don't get decremented

**Comment by marekmaskarinec** [comment]
There seem to be more problems with append. When I append stuff, it crashes, when I don't pass it another array.

This only happens sometimes though. I created a test, where I could append int to []int like this: `append(arr, 1)` without it crashing, but before I didn't have such luck. I have a suspicion, that it happens, when you try to append a struct.

**Comment by vtereshkov** [comment]
Very interesting! I didn't notice any crashes even when I replaced `append(arr, []type{element})` with `append(arr, element)` in `addtail()`. Do you have a real example that crashes or an instruction how to reproduce it?

**Comment by marekmaskarinec** [comment]
Hmmm. That is really weird. I remember having the crash in `addtail()`. It seems, I have a cursed pc. It could have been something entirely else though (but I remember having problems with append).

**Comment by vtereshkov** [comment]
Anyway, if you encounter a crash again, please file an issue. A crash due to reference counting bugs is much worse than a memory leak.

**Comment by marekmaskarinec** [comment]
Ok. I will. Can I just ask a question? Is it possible for errors to be like go's panic? It is really hard to debug, since you don't even have gdb. Or is it not possible/hard?

**Comment by vtereshkov** [comment]
Do you mean printing stack trace or a possibility to recover? A stack trace is in my plans, while deferring or recovery is definitely not.

**Comment by marekmaskarinec** [comment]
I meant printing stack tree. It would help a lot.

**Comment by vtereshkov** [comment]
Anyway, a runtime error, either unintentional or triggered by `error()`, always prints the line at which it occurred.

**Comment by marekmaskarinec** [comment]
Ok, cool. Just want to ask and not make a new issue, is there some kind of exit function?

**Comment by vtereshkov** [comment]
Do you mean a 'normal' exit without an error? Not yet. I cannot merely call C `exit(0)` because it would terminate the host application, not just the Umka script. So I need a carefully designed custom function that should respect garbage collection considerations.

**Comment by vtereshkov** [comment]
@marekmaskarinec Regardless of the reference counting bugs, I suppose your approach to collision detection is not quite correct. `append()` does not provide in-place appending. Any time you call `tails = append(tails, ...)`, Umka reallocates the whole array at a new place. So what you saved in `s` before is no longer related to the current `tails`, these items are just ghosts of the old `tails`.

The same thing happens in Go:
```
type ent = struct{ x int }

func main() {
	tails := []ent{}
	s := []*ent{}

	for i := 0; i < 10; i++ {
		tails = append(tails, ent{i})
		s = append(s, &tails[len(tails)-1])
	}
	
	s[9].x = 42
	fmt.Println(tails[9].x) // OK: prints 42	
	
	s[0].x = 42
	fmt.Println(tails[0].x) // BAD: prints 0
}
```

**Comment by vtereshkov** [comment]
@marekmaskarinec A simple solution I have found is to change the parameter type in `getcoll()` from `[]^ent` to `[]ent` and then to completely remove the global `s` in favour of a local `s` that is constructed at each iteration:
```
...
		// checking, if snake is out of bounds to kill him
		if head.p.x < 0 || head.p.x >= cam.w || head.p.y < 0 || head.p.y >= cam.h {
			die()
		}

		// checks for collisions in scene s
		s := append([]entity.ent{head, fruit}, tails)   // here it is
		
		coll = head.getcoll(s)
		switch coll {
		case 1:
			eatfruit()
		case 4:
			die()
		}	
...
```
As a bonus, we get rid of all those memory leaks. But of course this is not a solution to the memory leak problem.

**Comment by marekmaskarinec** [comment]
Interesting

**Comment by marekmaskarinec** [comment]
Appending it on the fly seeems like a good ideat tbh, although I'm not really sure, if it is needed to make it entities and not pointers. This will definitely help with bigger games, where you need to delete stuff, since you can for example have an enemy function and make it append to a global s. When enemy dies, function isn't called and it won't append anymore. This seems like a good idea. If I would keep giving it pointers, I should probably make a add function, that adds them in `tophat.cycle`, so there aren't any conflicts.

**Comment by vtereshkov** [comment]
@marekmaskarinec It's up to you. The key point is to build the 'scene' on the fly to avoid having dangling pointers. Whether to use entities or entity pointers is not so important. I used entities because
* They let me avoid memory leaks (this is my problem, not yours)
* Appending them can be done with one line of code
