### ISSUE TITLE
Convenience functions/macros for accessing function parameters from C

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#417]
Too many questions like _In what stack slot can I find my dynamic array parameter?_ 

And overall, mixing the API with ABI is not good, even if [documented](https://github.com/vtereshkov/umka-lang/blob/master/doc/api.md#calling-functions).

**Comment by skejeton** [comment]
While we can, I think the direct stack slot API should be replaced with as single parameter:

```
void externalFunction(UmkaCall *call) {
  int firstArg = umkaArg(call, 0);
  int secondArg = umkaArg(call, 1);
  umkaReturn(call, firstArg+secondArg);
}
```

What I am not sure about here is how we handle types, umkaArg needs to return some type where we can select the type, like an UmkaStackSlot, but this also needs to work for dynarrays.
One idea is to have a separate function for each type, but it can get pretty cumbersome.
