### ISSUE TITLE
Auto dereferencing doesn't work in `sort` closures.

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#431]
```
type Window* = struct {
  visible: bool
  title: str
  rect: rect::Rect
  order: int
}

var windows: map[str]Window

fn toggleWindow(title: str, rect: rect::Rect) {
  ordered := []^Window{}
  for _, w in windows {
    ordered = append(ordered, &w)
  }

  sort(ordered, {return a.order - b.order}) // error: Method order is not defined for ^Window
```

**Comment by vtereshkov** [comment]
For an array of type `[]T`, the `a` and `b` parameters are of type `^T`. Your `T` is `^Window`, so your `a` and `b` are `^^Window`. Umka doesn't do double implicit dereferencing.

**Comment by skejeton** [comment]
> For an array of type `[]T`, the `a` and `b` parameters are of type `^T`. Your `T` is `^Window`, so your `a` and `b` are `^^Window`. Umka doesn't do double implicit dereferencing.

Ah, gotcha.
