### ISSUE TITLE
Dangling pointers by premature releasing local variables

### ISSUE THREAD

**Issue by Mazdaywik** [vtereshkov/umka-lang#44]
In actual Umka version stack frames are allocated in heap instead system stack. If frame contains pointers, they are freeing on function return. But stack frame may alive after return — it may be saved by pointers to local variables. And the local variables can reference to dangling pointers:

```Golang
const (
  SIZE = 100
  LOOPS = 10
)

type (
  object = struct {
    x: [SIZE] int
  }
)

fn make_dangling(init: int): ^^object {
  po := new(object)
  for i := 0; i < SIZE; i++ {
    po.x[i] = init
  }

  ppo := &po
  return ppo
}

fn check(po: ^object, init: int) {
  i := 0;
  for i < SIZE && po.x[i] == init {
    i++
  }

  if i == SIZE {
    printf("%d Ok\n", init)
  } else {
    printf("%d Err\n", init)
  }
}

fn test1() {
  var oarr: [LOOPS] ^object

  for i := 0; i < LOOPS; i++ {
    ppo := make_dangling(i)
    oarr[i] = ppo^
    check(oarr[i], i)
  }
}

fn test2() {
  var oarr: [LOOPS] ^object

  for i := 0; i < LOOPS; i++ {
    ppo := make_dangling(i)
    oarr[i] = ppo^
  }

  for i := 0; i < LOOPS; i++ {
    check(oarr[i], i)
  }
}

fn main() {
  test1()
  test2()
}
```
Output:
```
D:\…\umka-lang\umka_windows_mingw>umka.exe dangling.um
0 Ok
1 Ok
2 Ok
3 Ok
4 Ok
5 Ok
6 Ok
7 Ok
8 Ok
9 Ok
0 Err
1 Err
2 Err
3 Err
4 Err
5 Err
6 Err
7 Err
8 Err
9 Ok
```
Download: [dangling.um](https://github.com/vtereshkov/umka-lang/files/6136456/dangling.um.txt).

**Comment by vtereshkov** [comment]
@Mazdaywik Now all variables that are pointers or contain pointers are zeroed upon leaving their scope. Your example produces the runtime error `Array or string is null` when trying to evaluate `po.x[i] == init`. I'm closing the issue. Please reopen it if you find this solution unsatisfactory.

**Comment by vtereshkov** [comment]
It appears to be safer to just throw a runtime error when a pointer to a local variable escapes from a function.
