### ISSUE TITLE
Inconsistentcy in forward declaration names causes confusion.

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#445]
```
fn do(a: int)

fn do(b: int) {
  printf("%v\n", a)
}

fn main() {
  do(32)
}
```

In the previous forward declaration we declared it to be `a`, but in the implementation it's `b`, you can only use the name from the forward declaration, which is confusing. There's 2 solutions: 

1. Allow the implementation to use `b`, disallow using `a`.
2. Force consistent parameter names.

**Comment by vtereshkov** [comment]
Implemented option 1.
