### ISSUE TITLE
Strange behaviour of pseudorandom numbers

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [vtereshkov/umka-lang#447]
#### Description

There is an issue with the first pseudo-random generated number. That number is slowly growing instead of being pseudo-generated. 
The rest of the numbers are fine.

#### Screenshots

![photo_2024-09-26 13 19 15](https://github.com/user-attachments/assets/92238fac-7d52-4022-aec8-d218315a9464)
![photo_2024-09-26 13 19 12](https://github.com/user-attachments/assets/f515e25e-4577-4582-8895-28ce8513e5d6)
![photo_2024-09-26 13 19 09](https://github.com/user-attachments/assets/ffb89671-b0d7-427d-8d91-80615cd24c23)
![photo_2024-09-26 13 19 08](https://github.com/user-attachments/assets/8ab40e3b-33b5-4aa6-ba76-b35aa20c0f46)
![photo_2024-09-26 13 19 05](https://github.com/user-attachments/assets/3095f533-e261-48f2-b8af-402c8ce87e05)
![photo_2024-09-26 13 19 02](https://github.com/user-attachments/assets/3664720a-6063-4108-942a-292e61fd58d8)

#### To Reproduce

```
import ("std.um")
fn main() {
    std::srand(std::time())
    for i := 0; i<10; i++ {
        a := std::frand() * 9
        b := round(a)
        printf("a: %v, b: %v\n", a,b)
    }
}
```

#### Expected behaviour

All of the numbers generated in a loop would be pseudo-random.

**Comment by skejeton** [comment]
Replacing it with something like xorshift128+ should be the solution I think. Just not Mersenne Twister, it's pretty slow and somewhat subpar compared to modern PRNG's

**Comment by vtereshkov** [comment]
First, I have to figure out what is the problem with my current generator. Is it inherently so bad or did I implement it wrong?
