### ISSUE TITLE
function no passing arguments

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#47]
I have a function:
```
fn (i: ^img) scale*(x, y: real32) {
	printf("umka vals: %f, %f\n", x, y)
	imgsetscale(x, y, i.handle)
}
```

and call it like this:
```
img.scale(1, 1)
```

But the output it prints is: `umka vals: 0.000000, 0.000000`

I tried with multiple values, not only 1.

**Comment by vtereshkov** [comment]
@marekmaskarinec I confirm the problem. While I'm working on it, you can use `real` (i. e., `double` in C) instead of `real32`.

**Comment by marekmaskarinec** [comment]
Ok, real seems to be working.
