### ISSUE TITLE
MinGW compilation

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#48]
I don't know, if this is really an umka problem, but I'm trying to corss compile something for windows using mingw. The compilation itself is ok, but then it can't load `libumka.dll`, even though I statically link `libumka.a`. How should I do compile it?

Here is, how I compile it: `x86_64-w64-mingw32-gcc src/*.c lib/windows/*.a -o tophat.exe -Wall -lm -Llib/windows -lumka -Ldl -Ilib/rawdraw -lopengl32 -lgdi32 -luser32`

**Comment by marekmaskarinec** [comment]
Ok, I resolved it by just putting the dll into the same folder, where the exe is. I don't want to ship a dll next to the exe. Is there a way to do it better?

**Comment by vtereshkov** [comment]
@marekmaskarinec Frankly speaking. I have never tried static linking. Probably you need a `.def` file along with `.a` and `.dll`.

**Comment by marekmaskarinec** [comment]
I tried linking the `.def` file, but it doesn't work. Windows is weird.

**Comment by marekmaskarinec** [comment]
Now, when I was copying `libumka.a`, I found out, it is 6.7 kb in size, while the linux build is 270 kb. Is it possible, you're compiling it incorrectly?

**Comment by vtereshkov** [comment]
Yes, I noticed that. I think it just points to DLL functions. I suppose there should be two different sorts of the `.a` files: "standalone libraries" and "DLL wrappers". This one is just a "wrapper". But it's just a conjecture.

**Comment by marekmaskarinec** [comment]
So is it possible to not need the dll to be there?

**Comment by vtereshkov** [comment]
[umka_windows_mingw.zip](https://github.com/vtereshkov/umka-lang/files/6178404/umka_windows_mingw.zip)

Try building with `libumka_static.a` instead of `libumka.a`. So add the following command-line options:
* for compiling: `-DUMKA_STATIC` 
* for linking: `-static -lumka_static`

**Comment by marekmaskarinec** [comment]
It still doesn't seem to work. This is my mess of compile flags: `x86_64-w64-mingw32-gcc src/*.c lib/windows/*.a -o tophat.exe -Wall -lm -Ldl -Ilib/rawdraw -lopengl32 -lgdi32 -Wl,-Bstatic -lpthread -Llib/windows -BUMKA_STATIC -static -lumka_static`

**Comment by marekmaskarinec** [comment]
Ok. I seem to have both normal .a file and static one in the same directory. Now I specified, I want libumka_static.a. It just throws a bunch of linker errors now.

```
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc30JrBg.o:bindings.c:(.text+0x75): undefined reference to `__imp_umkaAddFunc'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc30JrBg.o:bindings.c:(.text+0x90): undefined reference to `__imp_umkaAddFunc'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc30JrBg.o:bindings.c:(.text+0xab): undefined reference to `__imp_umkaAddFunc'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc30JrBg.o:bindings.c:(.text+0xc6): undefined reference to `__imp_umkaAddFunc'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc30JrBg.o:bindings.c:(.text+0xe1): undefined reference to `__imp_umkaAddFunc'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/cc30JrBg.o:bindings.c:(.text+0xfc): more undefined references to `__imp_umkaAddFunc' follow
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2b68): undefined reference to `__imp_umkaCall'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2b9b): undefined reference to `__imp_umkaAlloc'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2c6b): undefined reference to `__imp_umkaInit'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2d34): undefined reference to `__imp_umkaInit'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2d7e): undefined reference to `__imp_umkaCompile'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2da7): undefined reference to `__imp_umkaGetError'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2e03): undefined reference to `__imp_umkaGetFunc'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2e1c): undefined reference to `__imp_umkaRun'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ccrfsBme.o:run.c:(.text+0x2e2f): undefined reference to `__imp_umkaFree'```

**Comment by vtereshkov** [comment]
@marekmaskarinec At least you have a typo: `-BUMKA_STATIC` instead of `-DUMKA_STATIC`. Not sure it is enough to fix the problem, but having `-DUMKA_STATIC` is absolutely necessary.

**Comment by marekmaskarinec** [comment]
ooops. Happens. Now it works even without the dll. Should I close this?

**Comment by vtereshkov** [comment]
Sure. The conjecture of two different sorts of the `*.a` files appears to be confirmed. A "true" static library is just an archive with all the `*.o` files generated by the compiler.
