### ISSUE TITLE
How to save/load bytecode

### ISSUE THREAD

**Issue by jarroddavis6889** [vtereshkov/umka-lang#49]
Possible?

Thanks

Jarrod

**Comment by marekmaskarinec** [comment]
I think he said in one issue, that it isn't as easy as it sounds. Give me a minute and I will find it.

**Comment by marekmaskarinec** [comment]
Ok, found it in [#43](https://github.com/vtereshkov/umka-lang/issues/43#issuecomment-798785260)

**Comment by vtereshkov** [comment]
@jarroddavis6889 This is not currently planned, since it requires saving not only bytecode, but also the whole type hierarchy for RTTI and other things. This is not as easy as it may seem.

**Comment by jarroddavis6889** [comment]
hmm, ok then.
