### ISSUE TITLE
`array[:n]`, `array[n:]` and `array[n:o]` support

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#52]
Is this supported/does it have different syntax from go?

**Comment by vtereshkov** [comment]
Not yet supported. Array slices are not quite easy for garbage collection. Is it of high priority for you?

**Comment by marekmaskarinec** [comment]
Tbh yes. I could just make a delete function though.

**Comment by vtereshkov** [comment]
OK, I'll think of it. While slices are unavailable, please use `append()` or `delete()`.

**Comment by Mazdaywik** [comment]
Semantics of slices must be similar to Python or Golang?
* In Python slice applied to list (arrays in Python are named «lists») creates new indepent list. Changes of new list (e.g. assigning to items) don’t influense to old list and vice versa.
* In Golang slice creates new view of the array: changes of slice modifies original array and vice versa.

I think, Python semantics is easy to implement in Umka.

**Comment by vtereshkov** [comment]
@Mazdaywik Totally agree with you. Didn't know Python slices work in such a way. This is not what I would call a "slice" _per se_, though it's really easier to implement. It can be just a function like `a = slice(a, startIndex, stopIndex)` without any special syntax rules.

**Comment by Mazdaywik** [comment]
Python slices can appear in left-hand side in assignment:
```Python
>>> a = [1, 2, 3, 4, 5, 6]
>>> a[2:4] = [10, 20, 30, 40]
>>> a
[1, 2, 10, 20, 30, 40, 5, 6]
```

**Comment by Mazdaywik** [comment]
> This is not what I would call a "slice" _per se_…

Slice semantics in Perl and Python are same. Slice semantics in Golang and Fortran are same.

C++ standard library has `std::slice` and `std::slice_array` types but its usage is too specific: <http://cplusplus.com/reference/valarray/slice_array/>.

JavaScript and PHP uses library functions named `slice` ([JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice), [PHP](https://www.php.net/manual/en/function.array-slice.php)), semantics similar to Python, if I understood correctly.

I found article in Wikipedia: <https://en.wikipedia.org/wiki/Array_slicing>.
