### ISSUE TITLE
Weird error numbers

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#59]
I'm not sure, if this is umka's fault or mine, but my errors look something like this: `Umka error gamescn.um (1528899539, 32636): `.

**Comment by marekmaskarinec** [comment]
Ok. I updated umka and it works now. I thought, I was up to date.

**Comment by vtereshkov** [comment]
I have changed `UMKA_MSG_LEN` in `umka_api.h`. With the old file, you might have had this problem.
