### ISSUE TITLE
About REPL...

### ISSUE THREAD

**Issue by gvtret** [vtereshkov/umka-lang#6]
You know the logic of parsing and interpreting Umka better than I do. The question is, how expensive is it to implement a command-line REPL like Lua or Python?

**Comment by vtereshkov** [comment]
I didn't consider it yet. The interpreter runs a recursive descent parser that translates the source file (as a whole) into the virtual machine bytecode. Then the virtual machine executes either the `main()` function, or any other function specified by the user. So it is not obvious for me how to implement REPL easily.

By the way, I dislike the standard (not Web-based) Python/Lua REPL and cannot see how to use it for tasks other than doing simple arithmetic. Do you really need it for your project? Are you going to make a wrapper like Jupyter?

**Comment by ktbarrett** [comment]
I consider a REPL very useful in an embeddable scripting language. The ability to interactively program the main application using a REPL is crucial. It is also useful in the context of beginners trialing the language. 

How much would have to change to have the parser work on statements?

**Comment by vtereshkov** [comment]
@ktbarrett Do you mean a traditional (command-line based) REPL? Like this?
```
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> 2+2
4
> a = 5
> a * 3
15
>
```
I still think this way is inconvenient (and non-interactive) when one needs a multi-line script with nested control flow constructs. How to edit it? How to put a missing `{` several lines above?

Anyway, to interactively program the main application with Umka, one can just pass a source string buffer (instead of the external file) to `umkaInit()` and then call `umkaCompile()` and `umkaRun()` every time the user modifies the buffer. 

What I would really like to have is a web-based REPL (a kind of "Umka playground").

**Comment by ktbarrett** [comment]
> Do you mean a traditional (command-line based) REPL? 

Well that's not my interest, but it should be relatively easy to make that. Using Lua as an example, the actual Lua command line REPL is just a couple hundred lines of C. That's a testament to it's flexibility and good design. 

> I still think this way is inconvenient (and non-interactive) when one needs a multi-line script with nested control flow constructs. How to edit it? How to put a missing `{` several lines above?

IPython allows you to do this. That is what I would use as a golden model for a very featureful REPL. Every command opens an editable text box you can navigate around in. And offers tools like dumping your command buffer into a file to use as a script once you have proved something out.

If you wish to know my exact interest in Umka: I am a maintainer of [cocotb](https://github.com/cocotb/cocotb), which we use heavily at my place of work. I have grown frustrated with Python and I'm looking for an alternative language to embed in an HDL simulator. There aren't many embeddable statically-typed languages with good coroutine support, which made Umka stand out. The alternative being a .NET/Mono based language (perhaps Boo?).

> Anyway, to interactively program the main application with Umka, one can just pass a source string buffer (instead of the external file) to `umkaInit()` and then call `umkaCompile()` and `umkaRun()` every time the user modifies the buffer.

Thank you, I will look into it.

> What I would really like to have is a web-based REPL (a kind of "Umka playground").

That would be nice. I'm not sure what is involved, but you might be able to get Umka hosted on [repl.it](https://repl.it/).

**Comment by vtereshkov** [comment]
@marekmaskarinec Did you succeed with compiling the Umka interpreter into WASM with Emscripten? Do you consider it a feasible tool for making a web-based Umka playground?

**Comment by marekmaskarinec** [comment]
Compiling umka to wasm with emscripten worked on the first try. I can confirm the short script I use for testing works.

**Comment by vtereshkov** [comment]
The web-based playground is ready to use. However, waiting for https://github.com/emscripten-core/emscripten/issues/9183 to solve the `scanf()` issue.
