### ISSUE TITLE
Overriding bindings of std.um functions

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#60]
I need to provide my custom function for `fopen`. I could make a separate `tophat/io.um` module, but I think that would be weird. Is it ok to use `umkaBind` on `fopen`?

**Comment by vtereshkov** [comment]
I don't quite understand the problem. Do you want to make a custom wrapper for C `fopen()`? I think it's OK. Just don't name it `rtlfopen()` and don't redefine `fopen()` in `std.um`.

The "standard" `fopen()` in Umka is implemented like this:
```
// Umka
fn rtlfopen  (name: str, mode: str): File;  
fn fopen*    (name: str, mode: str): File {return rtlfopen(name, mode)}

// C
externalAdd(&comp->externals, "rtlfopen",   &rtlfopen); // umkaAddFunc() also uses externalAdd() under the hood

void rtlfopen(Slot *params, Slot *result)
{
    const char *name = (const char *)params[1].ptrVal;
    const char *mode = (const char *)params[0].ptrVal;

    FILE *file = fopen(name, mode);
    result->ptrVal = (int64_t)file;
}
```

**Comment by marekmaskarinec** [comment]
I just didn't realise, fopen is just a wrapper. I will just make it a wrapper around my own function.

**Comment by vtereshkov** [comment]
Ah, you thought `fopen()` was a built-in function. No, it's just a wrapper.
