### ISSUE TITLE
Methods requiring import

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#61]
I have a `audio.sound`, called `hitsnd` and it is defined in `global.um`. When I try using a method `play()` on it in another file, than `global.um`, I still need to import `tophat/audio.um`.

**Comment by vtereshkov** [comment]
@marekmaskarinec Please check the latest fix and reopen if it still fails.

**Comment by marekmaskarinec** [comment]
It still fails. I can't reopen.

**Comment by vtereshkov** [comment]
Can I see the branch (or just a ZIP archive) where it fails?

**Comment by marekmaskarinec** [comment]
You can recreate it in tophat, if you comment line 8 in examples/space-shooter/player.um.

Could I get an up to date version of libumka_static.a? You made some changes, that prevent me from using the old version (type casts).

**Comment by vtereshkov** [comment]
It seems that I had commented this line (`"tophat/audio.um"`) out before testing my fix. And the game runs fine. Maybe I should try the latest `tophat:master`.

**Comment by vtereshkov** [comment]
I cannot build the latest `master` due to the following errors:
```
src/audio.c:11:10: fatal error: ../lib/miniaudio.h: No such file or directory
 #include "../lib/miniaudio.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/tophat.h:13,
                 from src/bindings.c:9:
src/audio.h:4:10: fatal error: ../lib/miniaudio.h: No such file or directory
 #include "../lib/miniaudio.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/image.c:6:10: fatal error: ../lib/stb_image.h: No such file or directory
 #include "../lib/stb_image.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/light.c:4:
src/light.h:12:2: error: unknown type name 'uint32_t'
  uint32_t color;
  ^~~~~~~~
```

**Comment by marekmaskarinec** [comment]
For the first four, you need to run `make deps`. The last one is fixed by including `stdint.h` in `src/light.h`. I'm still not sure, if the windows build will work. I will try it, since I have the new library now.

**Comment by marekmaskarinec** [comment]
[windows_build.zip](https://github.com/vtereshkov/umka-lang/files/6444336/windows_build.zip)
try this one

**Comment by vtereshkov** [comment]
There are two problems with this build:
* It doesn't see the contents of the `tophat.dat` folder. To run the game, it needs to be copied right into this folder.
* The game crashes when I click `PLAY`.

**Comment by marekmaskarinec** [comment]
> • It doesn't see the contents of the tophat.dat folder. To run the game, it needs to be copied right into this folder.

I'm not sure, what you mean. Tophat.dat is used, when a game is packaged.

About the other error, I think it is a problem with linking opengl. I will look into it tomorrow.

**Comment by vtereshkov** [comment]
> I'm not sure, what you mean. Tophat.dat is used, when a game is packaged.

I mean, you check three locations: `game.um`, `main.um`, and `tophat.dat/game.um`, but not `tophat.dat/main.um`.

**Comment by marekmaskarinec** [comment]
> On the other hand, commenting out "tophat/audio.um" does not change anything.
Interesting. I will try it again.

> I mean, you check three locations: game.um, main.um, and tophat.dat/game.um, but not tophat.dat/main.um.

This should be fixed.

I think, we should move the compile issue here: https://github.com/marekmaskarinec/tophat/issues/15

**Comment by vtereshkov** [comment]
> This should be fixed.

Not sure.
```
	FILE *f;
	char scriptpath[20];
	if ((f = fopen("game.um", "r"))) {
...
	} else if ((f = fopen("main.um", "r"))) {
...
	} else if ((f = fopen("tophat.dat/game.um", "r"))) {
...
	} else {
		errprint("Could not find game.um. Make sure you are in a proper directory.");

		return 1;
	}
```

**Comment by vtereshkov** [comment]
Anyway, do we still have the method import problem? I cannot reproduce it. As I said, commenting out `"tophat/audio.um"` does not prevent the program from compiling (though it crashes afterwards for an unrelated reason). What error message do you get? Are you sure you have built `tophat` with the up-to-date  Umka version?

**Comment by vtereshkov** [comment]
@marekmaskarinec If this issue is no longer valid and you don't have any other urgent requests, I'll start preparing the 0.5.1 release.

**Comment by marekmaskarinec** [comment]
I fixed the way, submodules are updated and everything works now. I'm closing this.
