### ISSUE TITLE
Using slice on string

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#62]
I tried to use `slice` on string, and it gave me the incompatible type error. Then I tried casting it to `[]char`, like you would do in go, which gave me the invalid type cast error. Is there a way to slice strings?

**Comment by vtereshkov** [comment]
The `slice` function only applies to dynamic arrays now. So yes, I should either accept strings in `slice()`, or allow converting strings to dynamic arrays and vice versa. The second approach is probably better.

**Comment by vtereshkov** [comment]
Done. The `slice()` function now accepts strings. Please try it.

**Comment by marekmaskarinec** [comment]
Yes. It seems to work.
