### ISSUE TITLE
Type assertion with interfaces

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#63]
Is there a way to do that, or is it not implemented yet?

**Comment by vtereshkov** [comment]
Sure you can do it! Here is an excerpt from the language reference:
> If a pointer of type ^T is converted to the interface, the interface stores that pointer. If a non-pointer variable of type T is converted to the interface, the variable is first copied to a new memory location, and the interface stores the pointer to that location. **In any case, the interface can be converted back to the type ^T. If a conversion of the interface to some type ^S not equivalent to ^T is attempted, the result is null**.

So there is no special syntax for type assertions. They are just type casts from an interface type to a pointer type.

See an example in `tests/fnctools.um`:
```
sqr := fn (x, ctx: fnc.Any): fnc.Any {p := ^int(x); return p^ * p^}
```
Keep in mind that Umka doesn't currently have type switches, so you have to write something like this to simulate them:
```
if p := ^int(interf); p != null {
    ...
} else if p := ^real(interf); p != null {
    ...
} else {
    ...
}
```

**Comment by marekmaskarinec** [comment]
Thanks. It seems, like I missread it. I tried casting to the type, not pointer. I will try it tomorrow.

**Comment by vtereshkov** [comment]
Can we close this issue?

**Comment by marekmaskarinec** [comment]
Yes. We can.
