### ISSUE TITLE
Types are treated as the same

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#64]
I have two identical struct. `hbox` and `vbox`.

This is, how `hbox` looks:
```go
type hbox* = struct {
	children: []element
	padding, dimensions: rectangle.rect
	span: int
}
```

`vbox` is the same struct, but with a different name. They both a `calculate` function as defined by an interface. When I run the code, I get duplicate identifier error. Interesting is, that if I add additional field to on of the structs, it works.

**Comment by vtereshkov** [comment]
Agree with @Mazdaywik. Types in Umka are considered equivalent according to their actual structure rather than their names. But I'm curious to see the whole piece of code that causes the trouble.

**Comment by marekmaskarinec** [comment]
I already merged those two structs. It just seemed to me as a bug.

**Comment by vtereshkov** [comment]
I would say, it's not a bug, but a bad feature :) I'll try to make it better. Maybe we need stricter type equivalence rules for method receivers.

**Comment by vtereshkov** [comment]
@marekmaskarinec I implemented a stricter rule for method receiver type equivalence, though I didn't tested it on tophat. Please try it.

**Comment by marekmaskarinec** [comment]
As I said, I already merged those two structs into one. I was able to have two identical structs in a test file.

Aside from this, is there `fgetc`?

**Comment by vtereshkov** [comment]
Anyway, please ensure that other parts of your code are not broken with this change.

I don't have `fgetc()`, but you can try either `fscanf(f, "%c", &c)` or `std.fread(f, &c)`.

**Comment by marekmaskarinec** [comment]
It seems to be working.

**Comment by Mazdaywik** [comment]
```golang
type (
    named = struct {
        x: int
    }
    pnamed = ^named
)

fn (self: ^named) foo() {
    printf("%d", self.x)
}

fn (self: ^pnamed) boo() {
    printf("boo %d", self^^.x)
}

fn main() {
    var n: named
    var p: pnamed
    n.x = 100

    n.foo()

    p = &n
    p.boo()
}
```
```
Error hello.um (24, 10): Unknown field boo
```
Is it expected?

**Comment by marekmaskarinec** [comment]
I think, this is the same as this issue: https://github.com/vtereshkov/umka-lang/issues/42

**Comment by vtereshkov** [comment]
@Mazdaywik I think this is neither structural type equivalence issue, nor a manifestation of #42 (as suggested by @marekmaskarinec). 

The only reason is the implicit dereference rule: `p.x` is the same as `p^.x` for a pointer `p`. If methods `f()` are defined for both `^T` and `^P` where `P = ^T`, then `p.f()` gets ambiguous.

This problem is effectively solved in Go:
> A receiver base type cannot be a *pointer* or interface type

I'll do the same thing.

**Comment by Mazdaywik** [comment]
It is expected behavior:
```golang
type (
    a1 = [10]int
    a2 = [10]int
    a3 = a2
)

fn (self: ^a1) foo() {
    printf("a1 %d\n", self[0])
}

fn (self: ^a2) foo() {
    printf("a2 %d\n", self[0])
}

fn (self: ^a3) foo() {
    printf("a3 %d\n", self[0])
}

fn main() {
    var x: [10]int
    x[0] = 100

    var py: ^a1
    py = &x
    py.foo()

    var pz: ^a2
    pz = &x
    pz.foo()

    var pq: ^a3
    pq = &x
    pq.foo()
}
```
```
a1 100
a2 100
a3 100
```
But `x.foo()` (as expected) is don’t work.

**Comment by Mazdaywik** [comment]
Do a receiver type must be only pointer to sturcture?
```golang
type (
    RealFunc = fn(x: real): real
)

fn square(x: real): real {
    return x*x
}

fn sin_(x: real): real {
    return sin(x)
}

fn (self: ^RealFunc) twice(x: real): real {
    return self^(self^(x))
}

fn main() {
    var f, g: RealFunc
    f = sin_  /* `f = sin` is don’t work */
    g = square
    printf("%f\n", f.twice(1))
    printf("%f\n", g.twice(1))
}
```
```
Error hello.um (21, 27): Method twice is not found, structure expected to look for field
```

**Comment by marekmaskarinec** [comment]
I might be wrong again, but I think we have an issue for that already.
> Umka doesn't distinguish between declaring type aliases (type T = S in Go) and new types (type T S).

This might be the case here.

**Comment by Mazdaywik** [comment]
Method of function pointer can’t be called directly (see comment above), but can be called thru an interface:
```golang
type (
    RealFunc = fn(x: real): real

    Twiceable = interface {
        twice(x: real): real
    }
)

fn square(x: real): real {
    return x*x
}

fn sin_(x: real): real {
    return sin(x)
}

fn (self: ^RealFunc) twice(x: real): real {
    return self^(self^(x))
}

fn main() {
    var fi, gi: Twiceable
    fi = RealFunc(sin_)  /* RealFunc(sin) is don’t work */
    gi = RealFunc(square)
    printf("%f\n", fi.twice(10))
    printf("%f\n", gi.twice(10))
}
```
```
-0.517581
10000.000000
```
If we write
```golang
…
    fi = RealFunc(sin)
…
```
we got the error:
```
Error hello.um (23, 23): ( expected but ) found
```

**Comment by vtereshkov** [comment]
@Mazdaywik Your examples may seem weird, but at least I think they cannot violate memory safety. 

Go also uses structural type equivalence, but with a special case that rules out many problems highlighted by your examples:
> A _defined type_ [i.e. a type that has an identifier] is always different from any other type.

However, a naive implementation of this special case causes new problems. For example, `fn square(x: real): real` is no longer a `RealFunc`. To solve them all, perhaps I'll have to introduce the concept of an _underlying type_ etc.

I think I'll revisit the problem only if it causes a segmentation fault or other serious failures.

**Comment by vtereshkov** [comment]
Type equivalence rules are now stricter. Any declared types that have different identifiers are considered different.

@marekmaskarinec It makes sense to re-check `tophat`.

**Comment by marekmaskarinec** [comment]
Sorry for late response. Tophat works.
