### ISSUE TITLE
Inconsistent type casts

### ISSUE THREAD

**Issue by vtereshkov** [vtereshkov/umka-lang#69]
Currently the following type casts for character data are allowed:
```
^[]char ---> ^[N]char <--> str

 []char <---  [N]char
```
There is no way to convert `str` to `[]char` if its length is unknown.

**Comment by vtereshkov** [comment]
Now the type cast diagram is as follows:
```
^[N]char <--> str

 []char <-->  [N]char
```

**Comment by vtereshkov** [comment]
@marekmaskarinec I draw your attention to this issue. For example, one option I consider is to replace
```
^[N]char <--> str
```
with
```
[N]char <--> str <--> []char
```
It may break backward compatibility.

**Comment by marekmaskarinec** [comment]
I totally agree with this change. What would it break?

**Comment by vtereshkov** [comment]
For example, `s := str(new([256]char))` would no longer work, since `^[256]char` would not be compatible with `str`. So I have to carefully think before doing this.

**Comment by vtereshkov** [comment]
Now the type cast diagram is as follows:
```
[N]char <-->  []char <--> str
```

**Comment by vtereshkov** [comment]
@marekmaskarinec Please check the latest version. If it's OK, I'll close this issue.

**Comment by marekmaskarinec** [comment]
Everything seems to work fine in tophat, but I found out, you can't iterate over a string using `in`

```python

fn main() {
    string := "this is a test"

    for _, s in string {
        printf("%c\n", s)
    }
}
```
Produces: `Runtime error test.um (5): Dynamic array is null`

**Comment by vtereshkov** [comment]
@marekmaskarinec That's strange. I get
```
C:\Users\Vasiliy\Desktop\umka-lang-master\umka_windows_mingw>umka.exe test.um
t
h
i
s

i
s

a

t
e
s
t
```

**Comment by marekmaskarinec** [comment]
Tested on another pc and it works fine. I will try it again.

**Comment by marekmaskarinec** [comment]
Ok. I ran make clean and it works.
