### ISSUE TITLE
Function with multiple return values need to be assigned

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#70]
I have this method:
`fn (t: ^twn) get*(time: int): (bool, real)`

When I want to call it, but not get any of the values, I get this error:
`Umka error game.um (47, 1): List assignment expected`

When I try assigning it to `_, _`, I get this error: `Umka error game.um (47, 1): Incompatible types real and bool`

**Comment by vtereshkov** [comment]
In Umka, there is no "name placeholder", so `_` is just an identifier. Hence, the second approach will not work. But I wonder why the first approach is not working either. Looks like a bug.

**Comment by marekmaskarinec** [comment]
Would it be possible to add something like `_`? It can be very useful.
