### ISSUE TITLE
Memory leak on runtime error during method call (specifically, `printf`) 

### ISSUE THREAD

**Issue by iotasieve** [vtereshkov/umka-lang#74]
OS: Linux x64
Arch: x86_64

(Fresh build)

```go
type Example = struct {}

fn (self: ^Example) print(): int {
    printf("%d", 0.4);
    return 0;
}

fn main() {
    something := Example {};
    something.print();
}
```

Such code results in a Runtime memory leak 
```
Runtime error hello.um (6): Incompatible types int32 and real in printf()
Warning: Memory leak at 0x7fe33b1fb800 (3 refs)
```
This isn't as significant in case where it's just the language runtime, but if it's going to be embedded somewhere, this is a problem

**Comment by vtereshkov** [comment]
@iotasieve I think this is not a severe problem. The leaks are detected by the interpreter itself (when calling `umkaFree()` from C) and the memory is immediately freed. After `umkaFree()`, all the leaked memory is returned to the OS.

**Comment by iotasieve** [comment]
Hmm I see, the message has confused me a bit
