### ISSUE TITLE
Segmentation fault when slicing a string

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#77]
I replaced this:
```go
fn (l: ^lexer) lex_str(): str {
	out := ""
	for true {
		c := l.get()

		if l.pos > 1 && c == '"' && l.inp[l.pos-2] != '\\' {
			break
		}

		out += c
	}
	return out
}
```
With this:
```go
fn (l: ^lexer) lex_str(): str {
    start := l.pos
    for true {
        c := l.get()

        if l.pos > 1 && c == '"' && l.inp[l.pos-2] != '\\' {
            break
        }
    }
    return slice(l.inp, start, l.pos-1)
}
```

And it causes a segmentation fault in `doBasicDeref`. It happened after about 500 executions of the function. `l.pos - 1` isn't bigger than `len(l.inp)`.

**Comment by vtereshkov** [comment]
Interesting? Is the whole code that causes the error too large?

**Comment by marekmaskarinec** [comment]
> Is the whole code that causes the error too large?

What do you mean by too large? It is about 200 lines and available in the libs repo (json.um).

> And did you see any warnings before the crash?

Nope. None at all.

**Comment by vtereshkov** [comment]
And what test data did you use?

**Comment by marekmaskarinec** [comment]
I used a file similar to `tests/bench.json`, but three times bigger. I'm not sure, if the error happens even with the smaller one.

**Comment by vtereshkov** [comment]
Hmm, with `tests/bench.json` I get `error: top level type can only be an object or an array`.

**Comment by marekmaskarinec** [comment]
Could you:
- Show the first few lines of bench.json
- add the code on line 236 under the line 257

**Comment by vtereshkov** [comment]
Oh, it was because of the wrong path to `bench.json`. The file was not actually read.

**Comment by vtereshkov** [comment]
I have fixed it. It was a rather stupid bug. Please check.

By the way, I still don't understand how to get a meaningful final result from parsing `tests/bench.json`. The array has zero length.

**Comment by marekmaskarinec** [comment]
> I have fixed it. It was a rather stupid bug. Please check.

Yes. It works now.

> By the way, I still don't understand how to get a meaningful final result from parsing tests/bench.json. The array has zero length.

Thanks for pointing it out. It should be pushed in a bit.

Should I close this?
