### ISSUE TITLE
How to compile the '3dcam' example?

### ISSUE THREAD

**Issue by bentxt** [vtereshkov/umka-lang#8]
Hi, 
How to compile the embedded example in 3dcam.c? 
Thanks
Ben

**Comment by vtereshkov** [comment]
One of the ways to compile it under Windows is the following: 
* Build or download the Umka distribution (`umka_..._windows_mingw`).
* Copy 3D cam example files (`3dcam.c`, `3dcam.um`) to `umka_..._windows_mingw\examples`
* Copy Umka distribution files (`libumka.dll`, `libumka.a`, `umka.exe`, `umka_api.h`) to the same folder
* Copy [raylib](https://github.com/raysan5/raylib/releases/tag/3.0.0) distribution files (`libraylib.dll`, `libraylib.dll.a`, `raylib.h`) to the same folder
* Rename `libraylib.dll.a` to `libraylib.a`
* Copy GCC runtime files (`libgcc_s_seh-1.dll`, `libwinpthread-1.dll`) to the same folder
* Run `gcc -O3 -Wall -c 3dcam.c` from the same folder
* Run `gcc 3dcam.o -o 3dcam.exe -static-libgcc -static -L%cd% -lm -lumka -lraylib` from the same folder

Building under Linux is similar, except that you need not rename `libraylib.a` or copy GCC runtime files, and the last command should be `gcc 3dcam.o -o 3dcam -static-libgcc -L$PWD -lm -lumka -lraylib -Wl,-rpath,'$ORIGIN'`

**Comment by vtereshkov** [comment]
@bentxt Did you manage to compile it? Can we close the issue?
