### ISSUE TITLE
Warning: Dangling pointer

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#80]
I'm making a game and I'm using interfaces in it. I get `Warning: Dangling pointer at` a lot. Everything works except for low framerates on windows caused by the excessive printing.
This is the interface:
```go
type Obstacle = interface {
    draw()
    get_ent(): ^entity.ent
    handle()
}
```
This code causes the problem:
```go
    for len(obstacles) < max_obstacles {
        r := std.rand()%3

        switch r {
        case 0:
            obstacles = append(obstacles, mk_saw(std.rand()%global.cam.w - global.cam.w/2, global.cam.y-global.cam.h/2 - std.rand()%20, std.frand()/12+0.01, std.rand()%global.cam.w/2 - global.cam.w/2 + 5, std.rand()%global.cam.w/2 - 5))
        case 1:
            obstacles = append(obstacles, mk_log(std.rand()%global.cam.w - global.cam.w/2, global.cam.y-global.cam.h/2 - std.rand()%20, std.frand()/8+0.06, 1)) // TODO up going logs
        case 2:
            obstacles = append(obstacles, mk_pile(std.rand()%global.cam.w - global.cam.w/2, global.cam.y-global.cam.h/2 - std.rand()%20))
        }
    }
```

Is there a fast solution for fixing this? If not, could I atleast receive libumka_static.a without the printing?

**Comment by marekmaskarinec** [comment]
Update: I was able to build build tophat that doesn't throw this warning. Crisis averted. I would still be interested in why this causes this problem.

**Comment by vtereshkov** [comment]
Very interesting! But I think I need the whole context (project source?) to determine what is happening here. By the way, what have you done to workaround the problem?

**Comment by marekmaskarinec** [comment]
> But I think I need the whole context (project source?) to determine what is happening here

https://github.com/marekmaskarinec/jam-submissions/blob/main/connected/game.um

> Just commented out the line that prints the warning

Yes.

**Comment by vtereshkov** [comment]
I tried to fix it, but could not run it with tophat. Please check the fix with the `Dangling pointer` warning enabled.

**Comment by vtereshkov** [comment]
It seems that the problem is still there. But the behavior is slightly different now.

**Comment by vtereshkov** [comment]
Now should be fixed. Please check.

**Comment by marekmaskarinec** [comment]
It is ok now.
