### ISSUE TITLE
'umka_ident.c/identFind' is slow when there are many identifiers:

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#84]
The following script generates another script which demonstrates the problem, 'genSilly.um':
```
import "path/to/std.um"

const N = 4000;

fn main() {
    var f: std.File = std.fopen("silly.um", "wb");

    for a := 0; a < N; a += 1 {
        fprintf(f, "fn f%d(): int { return %d; }\n", a + 1, a + 1);
    }

    fprintf(f, "fn main() {\n");
    fprintf(f, "    var x: int = 0;\n");
    for a := 0; a < N; a += 1 {
        fprintf(f, "    x += f%d();\n", a + 1);
    }
    fprintf(f, "    printf(\"%%d\\n\", x);\n");
    fprintf(f, "}\n");

    std.fclose(f);
}

```

silly.um:
```
fn f1(): int { return 1; }
...
fn f4000(): int { return 4000; }
fn main() {
    var x: int = 0;
    x += f1();
    ...
    x += f4000();
    printf("%d\n", x);
}
```

I did not use a profiler but I think 'umka_ident.c/identFind' having to traverse a linked list for every identifier is what's taking most of the time (probably).
I think blocks that end up having "lots" of identifiers (usually the global scope) need to switch to a hash table lookup instead of linear search.

It is not completely unrealistic for a module to have [thousands of identifiers](https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/api/GL/glcorearb.h).

**Comment by vtereshkov** [comment]
Not sure this is important, since the identifier name list is searched only when the script is compiled to bytecode, so it doesn't affect execution performance.
