### ISSUE TITLE
calling imported functions from C

### ISSUE THREAD

**Issue by sandthief965** [vtereshkov/umka-lang#9]
I'm trying to call a function imported from the compiled file, does Umka support this?

```go
fn foo() {printf("hello from b!")}
```
```go
import "b.um"

fn main() {}
```
```c
umkaInit("a.um", 1024 * 1024, 1024 * 1024, 0, NULL);
b = umkaGetFunc("b.foo");
```

**Comment by vtereshkov** [comment]
Please try the latest commit. Don't forget to mark `foo` as exported from `b`:
```
import "b.um"

fn main() {}
```
```
fn foo*() {printf("hello from b!")}
```
```
#include "umka_api.h"

int main()
{
    umkaInit("a.um", 1024 * 1024, 1024 * 1024, 0, NULL);
    umkaCompile();
    int b = umkaGetFunc("b.um", "foo");
    umkaCall(b, 0, NULL, NULL);
    umkaFree();
    return 0;
}
```

**Comment by sandthief965** [comment]
Thank you! it works

**Comment by vtereshkov** [comment]
@sandthief965 I got rid of the global compiler state, so now it should be thread-safe. I modified the API accordingly, so now your example should look like 
```
#include "umka_api.h"

int main()
{
    void *umka = umkaAlloc();
    umkaInit(umka, "a.um", 1024 * 1024, 1024 * 1024, 0, NULL);
    umkaCompile(umka);
    int b = umkaGetFunc(umka, "b.um", "foo");
    umkaCall(umka, b, 0, NULL, NULL);
    umkaFree(umka);
    return 0;
}
```
It would be great if you test it.

**Comment by sandthief965** [comment]
Tested it on macOS Catalina, Works like a charm!
Next is testing it on the Wii, is there anything you think that would prevent it from running on a PPC CPU?

**Comment by vtereshkov** [comment]
@sandthief965 Thank you! I have never tested it on macOS. As for PowerPC, I expect some problems, as this is a 32-bit (not 64-bit) architecture. I'm already working on the full 32-bit support, but it will take some time. If this is a real use case, I will raise the priority of this task.

**Comment by vtereshkov** [comment]
@sandthief965 I have committed some changes that allow Umka to run correctly on both 64-bit and 32-bit Windows. It successfully passes all my tests. Hope that other 32-bit platforms are now supported as well. Anyway, please recheck both macOS and PowerPC (Unix?) versions.

**Comment by vtereshkov** [comment]
@sandthief965 Do we need to open a separate issue on 32-bit support?

**Comment by sandthief965** [comment]
I'm so sorry for the late reply
So It works on 64 bit macOS
However when compiled for PowerPC on the Wii https://en.wikipedia.org/wiki/Wii
it seems to return the wrong ident in the function ```compilerGetFunc()```
What do you think could be causing this?

Yeah I think making a new issue for the Wii platform would be great

**Comment by vtereshkov** [comment]
@sandthief965 Very interesting! Please open a new issue and describe what exactly this function returns (it is a plain integer number). To simplify the debugging, please also try to save the assembly code: call `umkaAsm` after calling `umkaCompile` and pass a sufficiently large (e.g. 100 kbyte) char buffer pointer to store the contents. I suppose you are using the latest Umka version from the `master` branch.
