### ISSUE TITLE
Calling a function with 'umkaCall' that takes a 'real32' parameter doesn't seem to work.

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#90]
app.c:
```
...
int fnId = umkaGetFunc(um, NULL, "printReal32");
UmkaStackSlot params[1];
params[0].realVal = 3.14159;
UmkaStackSlot result;
umkaCall(um, fnId, 1, params, &result));
...
```

script.um:
```
fn printReal32(x: real32) {
    printf("%f\n", x);
}

fn main() {
    printReal32(3.14159); // this call prints '3.141590'
    // but the 'umkaCall' to 'printReal32' prints '-192530768169799846490900791296.000000'
}

```

**Comment by vtereshkov** [comment]
Yes, this is a known problem. Stack slot structure doesn't allow passing `float`s directly. The `realVal` field is `double`, not `float`. If you need a workaround, you can try using
```
float x = 3.14159;
params[0].uintVal = *(uint32_t *)&x;
```

**Comment by luauser32167** [comment]
Why not simply add a ```real32Val``` field to ```UmkaStackSlot```?

```
typedef union
{
    int64_t intVal;
    uint64_t uintVal;
    int64_t ptrVal;
    double realVal;
    float real32Val; // <-- new field
} UmkaStackSlot;

```

Perhaps also a ```char const* strVal``` field, instead of doing ```param[x].ptrVal = (int64_t)"some string"```.

**Comment by marekmaskarinec** [comment]
Why not just use reals? You can do a small wrapper function, that converts real32 to reals and the other way.

> Perhaps also a char const* strVal field, instead of doing param[x].ptrVal = (int64_t)"some string".

What would be the benefit over using ptrVal? Casting a strings to intptr isn't that big of a problem.

**Comment by vtereshkov** [comment]
> Why not simply add a real32Val field to UmkaStackSlot?
> Perhaps also a char const* strVal field, instead of doing param[x].ptrVal = (int64_t)"some string".

Because it may fail on 32-bit platforms. In the first version of Umka, `ptrVal` was `void *`. It worked pretty well on 64-bit systems (both Windows and Linux) but crashed on 32-bit platforms, probably due to alignment issues. Then I decided to keep all `UmkaStackSlot` fields strictly 64-bit on all platforms. Declaring `ptrVal` as `int64_t` may seem clumsy, but it works.

**Comment by luauser32167** [comment]
Does it also fail for the ```real32Val``` field?

There seems to be a difference when assigning directly to the field ```real32Val```:
```
typedef union
{
    int64_t intVal;
    uint64_t uintVal;
    int64_t ptrVal;
    double realVal;
    float real32Val;
} UmkaStackSlot;

static uint64_t
umka_real32ToInt64(float x) {
    union {
        uint64_t u;
        float f;
    } u;
    u.u = 0;
    u.f = x;
    return u.u;
}

static void
test(void) {
    UmkaStackSlot x = {0}; printf("%016jX\n", x.uintVal); // 0000000000000000
    x.realVal = 6.28; printf("%016jX\n", x.uintVal); // 40191EB851EB851F
    // x.real32Val = 3.14159f; printf("%016jX\n", x.uintVal); // 40191EB840490FD0, here we have garbage in the top bits from the previous assignment, is this a problem though?
    x.uintVal = umka_real32ToInt64(3.14159f); printf("%016jX\n", x.uintVal); // 0000000040490FD0
}
```

The reason for the ```umka_real32ToInt64``` (i.e using a union) instead of using the ```*(uint32_t *)&x``` bitcast, is because the later is UB, I think.

**Comment by vtereshkov** [comment]
> Does it also fail for the real32Val field?

I didn't check that, but I nevertheless consider it a problem, since I don't know whether this `real32Val` will have "left" or "right" alignment within a 64-bit space.

**Comment by luauser32167** [comment]
So the union type punning is a gcc extension... and instead memcpy can be used:
```
static uint64_t
umka_real32ToInt64(float x) {
    uint32_t y;
    memcpy(&y, &x, sizeof(float));
    return (uint64_t)y;
}
```

>I didn't check that, but I nevertheless consider it a problem, since I don't know whether this real32Val will have "left" or "right" alignment within a 64-bit space.

I don't know what left/right alignment is.

**Comment by vtereshkov** [comment]
Seems to be fixed. Better than nothing.
