### ISSUE TITLE
Inconsistent rules for placement of curly brackets and parentheses.

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#96]
```
// ok
import (
    "A.um";
    "B.um"; )

// ok
import (
    "C.um";
    "D.um";
)


// ok
const (
    kA = 1;
    kB = 2; )

// ok
const (
    kC = 1;
    kD = 2;
)


// not ok
// var xs: [3]int = [3]int{
//     10, 20, 30
// };
// ok
var xs: [3]int = [3]int{
    10, 20, 30 };


type Foo = struct {
    x, y, z: int;
};
// not ok
// var foo: Foo = Foo{
//     10, 20, 30
// };
// ok
var foo: Foo = Foo{
    10, 20, 30 };

```

**Comment by vtereshkov** [comment]
The rules are almost the same as in Go, and the "inconsistency" is related to the implicit semocolon rule. This is clearly stated in the language specification.

https://play.golang.org/p/x06mWarhr84

**Comment by luauser32167** [comment]
Go allows a trailing ',', Umka does not:

Umka:
```
var xs: [3]int = [3]int {
    10,
    20,
    30, // error: Too many elements in literal
};
```

Go:
```
var xs = [3]int {
    10,
    20,
    30, // ok
};
```

**Comment by marekmaskarinec** [comment]
There is already an issue for this, although I can't find it.

**Comment by vtereshkov** [comment]
@marekmaskarinec I think you mean #58. This is what the last comment by @luauser32167 is about. But it's not the same as the original "inconsistency".

**Comment by marekmaskarinec** [comment]
Yes. I meant it as a response to the last message.
