### ISSUE TITLE
User defined variadic functions are not supported.

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#98]
There is no mechanism to add a wrapper around a builtin variadic function, thus functions like ```errorf```, ```printfln``` and ```asprintf``` are not currently implementable in a ```script.um```.

**Comment by marekmaskarinec** [comment]
Is this really needed? You can define a function like `errorf` using `[]interface{}`. This is what I've come up with:
```go
fn errorf(msg: str, values: []interface{}) {
    b := strings.mk_builder()
    split := strings.split(msg, "~a")

    if len(values) != len(split) - 1 {
        error("incorrect number of values to errorf")
    }

    for i:=0; i < len(values); i++ {
        b.write_str(split[i] + repr(values[i]))
    }
    b.write_str(split[len(split)-1])

    printf("error: %s\n", b.to_str())
}

fn main() {
    errorf("expected ~a, but got ~a", []interface{}{12, []bool{true, false, true, true}})
    errorf("should work with no values", []interface{}{})
    errorf("this is incorrect error", []interface{}{"i shouldn't be here"})
}
```
Output:
```
error: expected 12 but got { true false true true } 
error: should work with no values

Runtime error tmp.um (11): incorrect number of values to errorf
```

**Comment by vtereshkov** [comment]
@marekmaskarinec That's a cool result! But if the original problem was about implementing `printf()` etc. as 'normal' variadic functions, it would be too cumbersome to write down all those `[]interface{}`.

However, variadic functions in Go do exactly the same as your `errorf()`, but with a better `...` syntax.
